### ISSUE TITLE
Code coverage of the backend should be improved

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-backend#1019]
At the moment the code coverage of the backend is below 96%. We want to include more tests to be up to 96% again.
(I have lowered the required code coverage to 95 %, this should be reverted.)

**Comment by reiterl** [comment]
One idea would be to exclude the migrations folder from the code coverage.

**Comment by reiterl** [comment]
I try to use the migrations/tests in the pytest, I think then the coverage is higher.

**Comment by reiterl** [comment]
The setup of migrations and the backend is different. The migrations excluded from the coverage.

**Comment by jsangmeister** [comment]
The code coverage of the current master seems to be 96.02%. This is too low to set it back to 96%, I think, but good enough that no work is necessary here. As long as we write thorough tests for every change/feature, the coverage is good enough, I think. Since we do not have 100% coverage like the datastore, the number is kind of arbitary anyway and I think debugging why we lost one percent point is too much work and too little reward. If we really wanted to improve the coverage, we would need to write more tests for all not-covered places, and the goal would then be to reach 100% and stay there. But as long as this is not the target, I think there is little benefit in this.

**Comment by r-peschke** [comment]
I agree with @jsangmeister and close it
