### ISSUE TITLE
Initial import

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#1035]
See #992 

It looks like that this new action does not match what I described here: https://github.com/OpenSlides/OpenSlides/issues/6257

The action should use the default initial data with the current migration index if the manage service does not provide any custom data. It should use the given migration index if any is given. It should also accept the first superuser password and set is after inserting all data.

Maybe some prerequisites came after the pull request was closed so we have to do it now. Please also see #1029 and keep the auth topic in mind.

**Comment by GabrielInTheWorld** [comment]
@normanjaeckel Please set - as always - the correct labels to see to which repo an issue belongs.

**Comment by jsangmeister** [comment]
From @r-peschke:

> To fulfill the backend requirements of this issue, there are following actions:
[organization.initial_data](https://github.com/OpenSlides/OpenSlides/wiki/organization.initial_import)
[user.set_password](https://github.com/OpenSlides/OpenSlides/wiki/user.set_password)
>
> @jsangmeister: I'm not quite sure whether they work on internal route without user permissions

The latter does and is tested (in https://github.com/OpenSlides/openslides-backend/pull/1029), the former should also work, but haven't tested it yet.

@normanjaeckel as @r-peschke wrote, these actions should suffice to do everything you want. If you really need it, we can of course also adjust the `organization.initial_import` action since it is only used by the manage service.

**Comment by r-peschke** [comment]
> See #992
> 
> It looks like that this new action does not match what I described here: [OpenSlides/OpenSlides#6257](https://github.com/OpenSlides/OpenSlides/issues/6257)
> 
> The action should use the default initial data with the current migration index if the manage service does not provide any custom data. It should use the given migration index if any is given. It should also accept the first superuser password and set is after inserting all data.

The action uses the global/data/initial-data.json from current backend, which is guaranteed to be consistent with the migrations, when there is no data given. Otherwise it uses the given data with its given migration index.
For setting a password use the common action to set the password, because this action is independently available and needed.
> 
> Maybe some prerequisites came after the pull request was closed so we have to do it now. Please also see #1029 and keep the auth topic in mind.

**Comment by normanjaeckel** [comment]
Ok, I will have a look.

**Comment by jsangmeister** [comment]
Closing this since there was no need for additional features.
