### ISSUE TITLE
committee.delete doesn't remove the cml-rights of users

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1071]
The CommitteeManagementLevel of user is a templateCharField, but no relation field. The reason, as far as I know, is the fact, that we want to have the ability of qualifying this relation, lets say to have not only CAN_MANAGE, but also CAN_DO_xy with the relation. Therefore technically the deletion of the committee has no impact on user.committee__management_level. We could implement this in committee.delete code with the disadvantage, that on recovery the user-CML could not be recovered.

Now this leads to problem of @emanuelschuetze that after deleting the default-committee you cant add a new one. This is because the admin still is the manager of the deleted committee. 

Workaround or more: With this Issue the calculated field handler will be modified, that it will recognize this fault on a per user base and will not modify such a left-over committee_management_level field.

**Comment by reiterl** [comment]
As far as I understand this workaround:
In user/committee__management_level the trash of a deleted committee will stay.
e.g. user/committee_$_management_level = ["1"]
       user/committee_$1_management_level ="can_manage"
DELETE committee/1
in user stays:
       user/committee_$_management_level = ["1"]
       user/committee_$1_management_level ="can_manage"
Right?

I dislike this workaround. This can lead to multiple problems, because then user/committee__management_level will be inconsistent.

**Comment by jsangmeister** [comment]
I would propose another approach: Updating only the template field and not the structured field. Example:

User 1 before deletion of committee 2:
```
"user/1": {
  "committee_$_management_level": ["2"],
  "committee_$2_management_level": "can_manage"
}
```
User 1 after committee deletion:
```
"user/1": {
  "committee_$_management_level": [],
  "committee_$2_management_level": "can_manage"
}
```
Since `committee/1` is deleted anyway, the extra information saved inside `user/1` does not hurt and will never be requested by any action that works on non-deleted models. When you restore the committee, you could potentially restore the CML, too.

To implement this, one would currently have to iterate all (!) users when a committee is deleted and check if the committee is present in the template field. This is too much work. Therefore, I would propose to extend our template-relation handling: Currently, each template field either has a `replacement_collection` or has a tag. This implicitely already separates the two types of fields. We could make two separate classes out of it (I'm talking `models.py` here, not `models.yml`) and for the former case, introduce an _additional relation_ in the replacement collection from where one could access all template fields which include it. This would mean the sarting scenario above would look the following:
```
"committee/2": {
  "users_with_committee_management_level":  [1]  // new relation, name TBD
},
"user/1": {
  "committee_$_management_level": [2],  // now an actual back relation, so no "strings as ids" anymore
  "committee_$2_management_level": "can_manage"
}
```
Now, when committee 2 is deleted, the normal relation handling can just go through all users listed in the new field and remove the committee from the template field.

I'm aware this would probably require a lot more work than your quick fix, but it also is a lot cleaner and future-proof.

Of course the name of the new back relation would have to be added somewhere in the `models.yml` so the relation handling knows where to look. Also, a migration would be necessary to add the back relation for all template fields with a replacement collection. I'm not sure if the work is worth it, but I at least wanted to write down my concept for it and hear what you think.

**Comment by r-peschke** [comment]
> I would propose another approach: Updating only the template field and not the structured field. Example:
> 
> User 1 before deletion of committee 2:
> 
> ```
> "user/1": {
>   "committee_$_management_level": ["2"],
>   "committee_$2_management_level": "can_manage"
> }
> ```
> 
> User 1 after committee deletion:
> 
> ```
> "user/1": {
>   "committee_$_management_level": [],
>   "committee_$2_management_level": "can_manage"
> }
> ```
> 
> Since `committee/2` is deleted anyway, the extra information saved inside `user/1` does not hurt and will never be requested by any action that works on non-deleted models. When you restore the committee, you could potentially restore the CML, too.
> 

So far, it is ok for me

> To implement this, one would currently have to iterate all (!) users when a committee is deleted and check if the committee is present in the template field.

We have the user_ids-Field in committee, we don't need ALL users, but maybe a lot

> This is too much work. Therefore, I would propose to extend our template-relation handling: Currently, each template field either has a `replacement_collection` or has a tag. This implicitely already separates the two types of fields. We could make two separate classes out of it (I'm talking `models.py` here, not `models.yml`) and for the former case, introduce an _additional relation_ in the replacement collection from where one could access all template fields which include it. This would mean the sarting scenario above would look the following:
> 
> ```
> "committee/2": {
>   "users_with_committee_management_level":  [1]  // new relation, name TBD
> },
> "user/1": {
>   "committee_$_management_level": [2],  // now an actual back relation, so no "strings as ids" anymore
>   "committee_$2_management_level": "can_manage"
> }
> ```
> 
> Now, when committee 2 is deleted, the normal relation handling can just go through all users listed in the new field and remove the committee from the template field.
> 
> I'm aware this would probably require a lot more work than your quick fix, but it also is a lot cleaner and future-proof.
> 
> Of course the name of the new back relation would have to be added somewhere in the `models.yml` so the relation handling knows where to look. Also, a migration would be necessary to add the back relation for all template fields with a replacement collection. I'm not sure if the work is worth it, but I at least wanted to write down my concept for it and hear what you think.

**Extension of template handling:**
The "relation" in this template-field is not even a relation field, but a TemplateCharField. We did it this way, because we wanted upgradeability to more than 1 right for committee. That's the reason I want to use a TemplateRelationField/TemplateRelationListField instead of a TemplateCharField. The problem is, that the used right (currently only 'can_manage') doesn't come from collection, it comes from a list. We implemented such a case with meeting/default_projector__id to projector/used_as_default_$_in_meeting_id, where the replacement is technically a list of strings.

**Comment by r-peschke** [comment]
There are a lot of possible combinations to realize this. In respect of relation handling I will implement the relation as follows:
user has a template field `committee_$_management_level`, which is a template/relation-list field. It uses the new `replacement-enum` with the possible rights, currently only `can_manage` and as value the list of committee_ids.
On the committee-side of the relation there is the template/relation-list-field `user_$_management_level`, which also uses the `replacement_enum` with `can_manage` and the user_ids as values of the structured field.
