### ISSUE TITLE
Change log level of warning in services/datastore/adapter.py 

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#1078]
https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/services/datastore/adapter.py#L251

I got this warning if I create a new user with the manage service (only with username and default_password which is accepted by the backend).

Please let me know what this warning is about and maybe exclude cases where it is obviously not valid.

**Comment by jsangmeister** [comment]
The warning (which has a typo...) warns about the following: Locking a collection field is possible either "normally" by providing a position or by additionally providing a filter. This has the advantage that changes to unrelated models can still occur without invalidating the current request.

This filter, however, has to be evaluated. This is significantly faster when an indexed field is present in the filter, since Postgres can then filter for this field first. The only field which we know about that should be generally indexed is `meeting_id`, therefore, if that is not present, a warning is issued since the request might potentially take a lot longer this way. When we have more performance data on large database, this can be newly evaluated whether we need this warning or not.

Excluding invalid cases (like creating users) is hard since the datastore adapter works on a lower level than the backend and does not know about models etc. But that's the reason why this is just a warning: The (backend) developer should check whether the filter can be improved; if that's not possible, the warning can generally just be ignored.

**Comment by ostcar** [comment]
This warning is in the production setup and therefore enjoining. I think this warning is good for the developers, but the end user does not need to see it, since he can not do anything about it.

Could you change the log level to something not shown in production?

**Comment by reiterl** [comment]
LoggingModule and Logger don't have a way to setLevel. So this is not easy possible.

**Comment by jsangmeister** [comment]
What do you mean? Just use `logger.debug` instead of `logger.warn` so the message is no longer displayed in production

**Comment by reiterl** [comment]
Yes, I can do that... But I cannot change the the logging level with setLevel.

**Comment by jsangmeister** [comment]
You don't need to do that, as the purpose of this issue is to just change the log level of this specific message

**Comment by reiterl** [comment]
The link above doesn't show a warning. Can you add the text of the warning, so i can find it in the adapter.

**Comment by reiterl** [comment]
Is it "Locking a collection field with a filter which does not contain meeting_id!"?

**Comment by jsangmeister** [comment]
> Is it "Locking a collection field with a filter which does not contain meeting_id!"?

yes

**Comment by reiterl** [comment]
Okay, I will fix this problem soon.
