### ISSUE TITLE
Can not reach internal action in production mode

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#1096]
https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/action/action_handler.py#L207

Looks like I can not reach the internal action `organization.initial_import` in production mode.

**Comment by peb-adr** [comment]
By looking at
- https://github.com/OpenSlides/openslides-backend/issues/1058
- https://github.com/OpenSlides/openslides-backend/pull/1029#issuecomment-977884715

I'm pretty sure @jsangmeister is currently still waiting for the definition of the shared secret, so that's why internal action are currently only reachable with `OPENSLIDES_DEVELOPMENT=1`.
So we have to agree how that secret is passed.

I assume it'd go / I propose something like this:
- `manage-service` and `backend` both get a docker secret, probably named like `internal_auth_password`
- the backend implements BasicAuth in the internal action handler, verifying the credentials `{ user: internal, password: $(cat ${INTERNAL_AUTH_PASSWORD_FILE}) }`
- the manage-service will provide these credentials in every request in the `Authorization`-Header

Perhaps having a user-field might not be necessary.

Also the INTERNAL_AUTH_PASSWORD_FILE env var might be a bit over the top for this and the path could just be assumed to be `/run/secrets/internal_auth_password`. However it would be consistent with how the other password secrets are passed, so I would prefer it like this.

@normanjaeckel 
@jsangmeister 
Thoughts?

**Comment by normanjaeckel** [comment]
Ok, I would like to implement this with `INTERNAL_AUTH_PASSWORD_FILE` and without a user. So it is consistant to the basic auth mechanism between manage tool and manage server.

**Comment by jsangmeister** [comment]
> Ok, I would like to implement this with `INTERNAL_AUTH_PASSWORD_FILE` and without a user. So it is consistant to the basic auth mechanism between manage tool and manage server.
> 
> So I will send a header `authorization` with the base64 encoded password file content as value.

Sounds good. I agree that a constant user which is the same for every request seems redundant.

**Comment by jsangmeister** [comment]
If that's okay for you I will wait here until you are finished implementing this feature. Then I will fix this all in once.
