### ISSUE TITLE
Implement the action `motion_state.sort`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1124]
See [motion_state.sort](https://github.com/OpenSlides/OpenSlides/wiki/motion_state.sort).

**Comment by jsangmeister** [comment]
Removing @r-peschke since I don't think he is working on this. @GabrielInTheWorld please don't randomly assign people since we use the assignment to keep track of which issue is currently being worked on on which is free.

**Comment by jsangmeister** [comment]
@GabrielInTheWorld does this really need to be a tree-like sorting? Because if so, we also need a `parent_id` analogous to e.g. agenda items, otherwise the tree structure will get lost when setting the weights linearily and we can use a linear structure in the payload from the start.

I don't see any reason why this needs to be tree-like and would argue that a linear layout (like e.g. for [chat groups](https://github.com/OpenSlides/OpenSlides/wiki/chat_group.sort)) should be enough, but feel free to correct me.

**Comment by GabrielInTheWorld** [comment]
> @GabrielInTheWorld does this really need to be a tree-like sorting? Because if so, we also need a `parent_id` analogous to e.g. agenda items, otherwise the tree structure will get lost when setting the weights linearily and we can use a linear structure in the payload from the start.
> 
> I don't see any reason why this needs to be tree-like and would argue that a linear layout (like e.g. for [chat groups](https://github.com/OpenSlides/OpenSlides/wiki/chat_group.sort)) should be enough, but feel free to correct me.

Oh, no, we don't need a tree-like sorting. This was made by accident. I've updated the action accordingly, so only a list of ids of motion_states are expected.
