### ISSUE TITLE
Action user.delete_or_remove_from_meeting

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1134]
The aim of the action is to remove a user from a specific meeting. If the user is only part of this meeting he should be deleted. Otherwise he should be removed from the meeting by removing him from all groups of the meeting.
See also [action user.delete_or_remove_from_meeting](https://github.com/OpenSlides/OpenSlides/wiki/user.delete_or_remove_from_meeting)

**Comment by jsangmeister** [comment]
Mmh, I'm not a fan of adding this kind of actions. If we continue to do this, we will get a huge amount of these "do this or else to that" kind of actions, which are hard to maintain and put additional burden on the backend.

Instead, this should also be possible purely client-sided together with https://github.com/OpenSlides/openslides-backend/issues/1135. The client asks for the scope for a specific user and, if it is `meeting`, can provide a "Delete" button. Otherwise (or even additionally), he provides a "Remove" button which issues an `user.update` action to remove the user from the current meeting. What do you think?

**Comment by r-peschke** [comment]
It's about a list of users not a single one.
Think of it as "remove the user from meeting".
And technically this is done by removing him from all the groups of the meeting. But if he is not involved anymore, he can be deleted at all.

We could do it this way and we don't need to realize Presenter call [get user scope](https://github.com/OpenSlides/openslides-backend/issues/1135). But this depends the benefit, the presenter call has.

**Comment by reiterl** [comment]
We don't need this action anymore and we don't want so double-action. So close it here. (Result of a discussion in daily.)
