### ISSUE TITLE
poll content_object

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#1161]
I have some questions for this already merged PR: https://github.com/OpenSlides/openslides-backend/pull/1154

Currently, the field [poll/content_object_id](https://github.com/OpenSlides/openslides-backend/blob/ba27ed3435d4246c339273df53857cdd033b6ca4/global/meta/models.yml#L2675-L2685) is not required.

Do I understand correctly, that there are no stand alone polls anymore but that every poll that does not belong to a motion or assignment belongs to a topic now? In this case, this field `required` has to be set to `true`.

Please also change the restriction wiki page: https://github.com/OpenSlides/OpenSlides/wiki/poll-restrictions

If the field is required, then you only have to change `Other/no content object` to `topic`.

This issue is urged, because this has to be fixed, before I make the required changes to the autoupdate-restrictor.

**Comment by jsangmeister** [comment]
No, content_object_id is still not required, only `topic` was added as an additional thing to be voted about, nothing else was changed.

**Comment by jsangmeister** [comment]
Additional info: The standalone polls are still not implemented in the client, but only in the backend, since it has not been a priority. However, it should be an easy task to extend the client accordingly, so we should IMO not remove this feature from the backend without need.

**Comment by ostcar** [comment]
I talked about this feature with @emanuelschuetze on our "Entwickertreffen" and if I am not mistaken, he does not need a stand alone poll, if there are topic-polls.

If a topic-poll is something different then a standalone poll, could you check that the restriction wiki is correct? Should everyone in a meeting see a topic-poll or should a user need to see linked topic or at least the agenda?

**Comment by jsangmeister** [comment]
> I talked about this feature with @emanuelschuetze on our "Entwickertreffen" and if I am not mistaken, he does not need a stand alone poll, if there are topic-polls.

I do not know about this, but as I said, it's easiest if we just leave it as-is with the option to add it easily later if needed. The initial thought behind this was that standalone polls could be used for short opinion gatherings like "What do we want to eat?"; things that are not on the agenda or even in the OS system. But I can imagine it is more a "community" feature for smaller assemblies instead of one for big conferences where everything has way more structure and order ;)

> If a topic-poll is something different then a standalone poll, could you check that the restriction wiki is correct? Should everyone in a meeting see a topic-poll or should a user need to see linked topic or at least the agenda?

I would guess that the permissions should be analogous to these of motion and assignment, meaning you need to see/manage the topic in order to see/manage the poll, but I don't know enough about our restriction management to be certain here.

**Comment by emanuelschuetze** [comment]
> I talked about this feature with @emanuelschuetze on our "Entwickertreffen" and if I am not mistaken, he does not need a stand alone poll, if there are topic-polls.

Correct. We want a topic poll only - no stand alone poll required because each poll is embeded in an agenda item / topic.

**Comment by ostcar** [comment]
@emanuelschuetze could you also tell who can see an manage the poll? See the restriction wiki for poll

**Comment by emanuelschuetze** [comment]
The user can see the poll if he can see the agenda (item). -> can you edit the wiki please?
The user can manage the poll if he has `poll.can_manage`.

**Comment by ostcar** [comment]
I can change the wiki. But first I have to know, if there still are stand alone polls. I created the PR #1170. Please merge it, when there are no stand alone polls anymore.

**Comment by jsangmeister** [comment]
As I said above, I would vote to leave everything as-is since it is the easiest solution: we do not need to change anything and we do not remove a feature which might or might not be used in the future. Because of that I would like to close https://github.com/OpenSlides/openslides-backend/pull/1170 - except if you have an argument to why this should be removed. Currently, I don't see how this is a blocker for you since everything's the same as before except a third collection was added to the generic field, which should not conflict with it beeing required or not.

**Comment by ostcar** [comment]
For the topic-poll, I have to change the restrictor code. When I do this, I want to remove all unnecessary code to make the existing code more clearer and remove potentially bugs.

If we remove stand alone polls, this code can/should be removed: https://github.com/OpenSlides/openslides-autoupdate-service/blob/main/internal/restrict/collection/poll.go#L57-L68 https://github.com/OpenSlides/openslides-autoupdate-service/blob/abd5fadab8afde6d535a8128277e8140c313ac6a/internal/restrict/collection/poll.go#L105-L117

Since @emanuelschuetze is sure, that we don't need stand alone polls now or in the foreseeable future, we should not keep the old unnecessary code.

In the very unlikely case, that we need the standalone polls in the future, then we can use the git history to revert the removal.

**Comment by jsangmeister** [comment]
Ok, sure.
