### ISSUE TITLE
Orga-wide mediafiles

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1173]
We need a way to handle mediafiles orga-wide. Currently, the collection `resource` is intended to fulfill such a feature. However, resources does not satisfy every requirement. Resources have to have something like `filename`, `title`, `parent_id` and something else, which mediafiles already have. 
Therefore, there are these options:

- We could enhance the resources to fulfill such requirements
- We could change mediafiles to deal with that requirements and delete resources

**Comment by reiterl** [comment]
What req?

**Comment by reiterl** [comment]
Not possible, if meeting_ids is `required` and `empty list` validating will throw an error.
I don't like the use of the organization id, it should be 1 or null, not an integer 0. Why is it needed anyway?
I don't think the URL is <media-prefix>/media/<meeting_id>/path . It is `"/system/media/get/<int:mediafile_id>"`.

**Comment by GabrielInTheWorld** [comment]
> Not possible, if meeting_ids is `required` and `empty list` validating will throw an error. 

Ah, okay. I thought, it then cannot be `null`, but then it will be `required: false`.

> I don't like the use of the organization id, it should be 1 or null, not an integer 0. Why is it needed anyway? 

As mentioned in the initial comment, we need some kind of mediafiles at the orga layer. There is already the collection `resource`, which is mentioned to use as "mediafiles" at the orga layer. However, `resource`s should have an optional `parent_id` and directories to represent a kind of file handling, which we already have within a meeting (with the `mediafile`s). Besides, `resource`s should also have something like `filename` and `title` to display them in a list.

> I don't think the URL is /media/<meeting_id>/path . It is `"/system/media/get/<int:mediafile_id>"`.

Well, if this is already the case, there is nothing to do for the path.

**Comment by GabrielInTheWorld** [comment]
As discussed with @reiterl and @r-peschke, `resource` and `mediafile` will remain and `resource` will be adjusted to match the requirements.

Things to do:
- [ ] The collection `resource` will be extended by these fields: `parent_id`, `is_directory`, `filename`, `title`, `child_ids` (these fields have the same type etc. like the one in the collection `mediafile`)
- [ ] Preferable is, that a user, who has the permission `mediafile.can_manage` within a meeting, can restrict a resource for specific groups within the meeting. This could be achieved by introducing something like `access_group_$_ids` as a template field.
- [ ] The actions `resource.move`, `resource.create_directory`, `resource.update` have to be implemented

**Comment by GabrielInTheWorld** [comment]
Things, which have to be discussed:
- We need a workflow to find already existing mediafiles within a meeting
- In addition, we need a way to "link" mediafiles to a meeting

**Comment by jsangmeister** [comment]
Latest proposal:

- `resource` will be merged into `mediafile`. The only field which needs to be added is `mediafile/token`. The relation `meeting_id` needs to be renamed (maybe something like `owner_id`? Open for other suggestions) and made generic with the target collections `organization` and `meeting` (potentially extendable in the future).
- For uploads:
  - `access_group_ids` can only be set if the owner is `meeting`. This means that orga-wide mediafiles can always be seen by all users - to control this, we would need some kind of orga-wide groups.
  - `token` can only be set if the owner is `organization`.
- Permissions:
  - if `token` is set, there are no permissions - the mediafile service can just deliver the file to any user, even if he isn't logged in.
  - if the owner is `meeting`, everything stays the same as before for mediafiles.
  - if the owner is `organization` and `token`is not set, every logged-in user can see the mediafile. This needs to be implemented in the presenter `check_mediafile_id`.

> * We need a workflow to find already existing mediafiles within a meeting

This is easy since the back relation `meeting/mediafile_ids` only contains the mediafiles for this meeting. Same for `organization/mediafile_ids` (renamed from `organization/resource_ids`)

> * In addition, we need a way to "link" mediafiles to a meeting

If we do not want all meetings to have access to orga-wide mediafiles, we could create a setting either in the meeting (if every meeting should control it themselves) or in the organization (if it should be controlled centrally) to adjust the meetings which have access to these files.

**Comment by r-peschke** [comment]
> Latest proposal:
> 
>     * `resource` will be merged into `mediafile`. The only field which needs to be added is `mediafile/token`. The relation `meeting_id` needs to be renamed (maybe something like `owner_id`? Open for other suggestions) and made generic with the target collections `organization` and `meeting` (potentially extendable in the future).
> 
>     * For uploads:
>       
>       * `access_group_ids` can only be set if the owner is `meeting`. This means that orga-wide mediafiles can always be seen by all users - to control this, we would need some kind of orga-wide groups.

We could define a token "public" for files that can be seen always for orga-wide mediafles and use the existing OrganizationManagementLevels to allow managing orga-wide mediafiles. We could think of a new one, but they are hierachic. In time we should think about a kind of orga-wide groups.

>       * `token` can only be set if the owner is `organization`.

Why not use them also on a meeting level?
> 
>     * Permissions:
>       
>       * if `token` is set, there are no permissions - the mediafile service can just deliver the file to any user, even if he isn't logged in.
>       * if the owner is `meeting`, everything stays the same as before for mediafiles.
>       * if the owner is `organization` and `token`is not set, every logged-in user can see the mediafile. This needs to be implemented in the presenter `check_mediafile_id`.

See above with token `public`  or OML-permissions.

> 
> 
> > * We need a workflow to find already existing mediafiles within a meeting
> 
> This is easy since the back relation `meeting/mediafile_ids` only contains the mediafiles for this meeting. Same for `organization/mediafile_ids` (renamed from `organization/resource_ids`)
> 
> > * In addition, we need a way to "link" mediafiles to a meeting
> 
> If we do not want all meetings to have access to orga-wide mediafiles, we could create a setting either in the meeting (if every meeting should control it themselves) or in the organization (if it should be controlled centrally) to adjust the meetings which have access to these files.

see above

**Comment by reiterl** [comment]
hmm, how to migrate `resources`?

**Comment by jsangmeister** [comment]
> hmm, how to migrate `resources`?

Every event which has a ressource as its target has to be updated to point to a mediafile. The id redirecting is a bit tricky, though. I _think_ however that we should be able to call `reserve_ids` from the migration code, since no OCC locking is done for this request and it is done atomic in a single transaction. Since the migration runs on the same database as the backend/datastore, this should work. Maybe @r-peschke has some thoughts about this, too?

**Comment by reiterl** [comment]
I talked to @emanuelschuetze  about the removing of the `resource` in the dev-daily.
We can just remove the `resource` collection without transferring data in the migration, as there is **no** `resource` data in the **customer database**s.

**Comment by r-peschke** [comment]
As @reiterl said, we don't need to migrate the resource-events, but we should remove them, if there are any. 
@GabrielInTheWorld talked about a web-logo taken from resource. Shouldn't we load this in the migration?

**Comment by GabrielInTheWorld** [comment]
> @GabrielInTheWorld talked about a web-logo taken from resource. Shouldn't we load this in the migration?

No. I just checked it. There is a resource registered in the database, but there is no resource physically. Please, just remove it.

**Comment by jsangmeister** [comment]
https://github.com/OpenSlides/OpenSlides/wiki/DE:-Vorschlag:-Mediafile-Rework
