### ISSUE TITLE
Migration: State after `migrate` seems inconsistent. It differs from using `finalize`.

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1185]
See test_0012_committee_user_relation.py, Test test_user_remove_add_2_stages.
For testing a break/shutdown during migration I used a migrate after migrating position 1.
If i include the 2 assert_model-statements for committee/1 and user/1000 , I expect them to work identical like they do after the finalize. But the user_ids and committee_ids are still empty. These values are filled in get_additional_events.l
Replacing the first migrate with finalize it works like expected.

**Comment by jsangmeister** [comment]
`migrate` does not write the migrated data back into the original table, but instead into a temporary one. You could either assert, like you do now, at the end that all data is correct, which should suffice, since you can explicitly assert for all positions. The alternative would be to write an assert function which checks the content of the temporary table, but since these are just copied on `finalize`, you check esentially the same like you do now.

Closing this since I don't think there is currently a problem here.
