### ISSUE TITLE
Full URL in password reset E-Mail

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#1187]
Currently, the password reset email only contains a path the to "password-forget"-handler. But the protocol and the domain is missing. So it is not possible to click on the link.

See also: https://github.com/OpenSlides/OpenSlides/discussions/6346

**Comment by jsangmeister** [comment]
We currently have 3 different url fields: `organization/url`, `meeting/url_name` and `meeting/users_pdf_url`. Since they (should) all share the same base url, I think the first should be enough. If one needs the meeting-specific URL (is that even necessary with the landing page of OS4 where you see all active meetings automatically?), you can just append the meeting id behind the organization's url. @GabrielInTheWorld is there any need to have all 3 or even 2 different urls or can this be unified?

This is however more or less independent of this issue. I think the solution should be to just prepend `organization/url` to the link (and to be careful about joining slashes).

**Comment by GabrielInTheWorld** [comment]
> We currently have 3 different url fields: `organization/url`, `meeting/url_name` and `meeting/users_pdf_url`. Since they (should) all share the same base url, I think the first should be enough. If one needs the meeting-specific URL (is that even necessary with the landing page of OS4 where you see all active meetings automatically?), you can just append the meeting id behind the organization's url. @GabrielInTheWorld is there any need to have all 3 or even 2 different urls or can this be unified?
> 

No, there is no need for this. The important one is the `organization/url`. I have talked to @emanuelschuetze and we agreed, that there is no need for `meeting/url_name`, `meeting/url` or `meeting/users_pdf_url`, anymore - as long as we have alternatives at the organization-layer. This means, we might need a field `organization/url_name`. The `users_pdf_url` is just the `organization/url_name`.

**Comment by jsangmeister** [comment]
What is the difference between `organization/url` and `organization/url_name`? Or did I just misunderstand your message and these two are the same and only one is needed (probably just `url` in this case)?

**Comment by jsangmeister** [comment]
> Well, maybe @emanuelschuetze could answer this question better than me, but if I understood him correctly, the `url` is the domain a request routes to on a server and the `url_name` is just a verbose name for that domain.
> 
> Currently, we have already the fields `meeting/url` and `meeting/url_name` and we only have to refactor them to `organization/url` and `organization/url_name`, I guess.

But the question is if this is necessary. I currently don't understand the difference between these fields and when to use each one. Can you or @emanuelschuetze provide an example for a "verbose" url? If this should just be analogous to the title of the instance, I would vote for renaming this field to remove the ambiguity of it.

**Comment by ostcar** [comment]
I also would like to get an answer from @emanuelschuetze But maybe I have an idea why there are two fields.

In the new vote-decrypt-service, I need an unique name for each OpenSlides-instance. I want to use the domain for that. For example `example.openslides.com`. Maybe that is the content of the field `organization/url_name`?

If I am correct, then I think we should change this. Either we only have the field `organization/url: https://example.openslides.com` and it is the job of the application to remove the protocol, or we have the two fields `organization/domain: example.openslides.com` and the field `organization/http_protocol: https`. But I don't think the later is necessary, since OpenSlides only supports https.

In any way, please tell me the content of `organization/1/url`. Does it contains a protocol prefix?

**Comment by jsangmeister** [comment]
Just talked with @emanuelschuetze and @GabrielInTheWorld and the field `organization/url` should suffice. I would argue it should include the whole URL like `https://example.openslides.com` (like it currently does, if I'm not mistaken) and if the application needs a "verbose" name without the protocol, it can go ahead and trim it.

As @emanuelschuetze remembered, the initial idea of `meeting/url_name` was to provide a verbose name for the meeting which can be used instead of the meeting's id in the url. So, if the `url_name` of meeting 1 was `meeting_a`, it could be reached under `https://example.openslides.com/1` as well as `https://example.openslides.com/meeting_a`. Since we did not pursue this feature and it is currently not needed, we can just remove this field together with the other ones.

Migration-wise, I would say to just drop the fields, since there is no meaningful way to incorporate them into other ones. So, a full description on what to do:

- Remove unneeded fields `meeting/url_name` and `meeting/users_pdf_url`
- Use `organization/url` in the email to provide a complete link
- Add `organization/url` to the action `organization.update` to be able to update it (probably only with superadmin privileges?)
- Reflect these changes in the client:
  - Change `meeting/users_pdf_url` to `organization/url`
  - Make `organization/url` updatable

Did I miss anything?
