### ISSUE TITLE
Error: List of speakers or poll countdown is not allowed to delete.

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-backend#1210]
Cannot remove both (predefined) countdows of default meeting (#1) in production mode.
Remove of countdown 1 works.

`Error: List of speakers or poll countdown is not allowed to delete. `

**Comment by emanuelschuetze** [comment]
Reproduced in fresh dev-mode setup in meeting 1.

**Comment by jsangmeister** [comment]
Yes, I investigated this a few weeks ago, this is intended behaviour. From our dev channel: "@gabriel @emanuel habe grad mal ein bisschen recherchiert und die speziellen countdowns (dokumentiert unter https://github.com/OpenSlides/OpenSlides/wiki/Countdowns) sind scheinbar eine Erweiterung der OS3-Config "agenda_couple_countdown_and_speakers". Der LOS-Countdown ist quasi genau das (wird gestartet, wenn jemand anfängt zu reden, und reset, wenn derjenige aufhört). Der Poll-Countdown ist das gleiche nur für Polls: Er wird gestartet, wenn der Poll gestartet wird, und gestoppt, wenn der Poll gestoppt wird. Die Setting, um diese Kopplung zu kontrollieren, ist "{list_of_speakers|poll}_couple_countdown". Die Countdowns können genauso angezeigt und gesteuert werden wie alle anderen auch, sie können eben nur nicht gelöscht werden, da sie immer wieder genutzt werden (für jede LOS bzw Poll)"

So, the visual representation on client side should be updated IMO: If the coupling is deactivated, the countdowns can be hidden; if it's activated, at least the delete button should be hidden and maybe a special indicator should be shown explaining why it can't be deleted.

If you do not want this feature at all, we can of course remove it, but I would imagine it is used quite often (at least by those who know about it), since this is the only way to issue an automatic start/stop to a countdown.
