### ISSUE TITLE
Update the actions `meeting.create` and `meeting.update`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1214]
I have noticed, that the actions `meeting.create` and `meeting.update` do not expect the key `set_as_template` (correct me, if I'm wrong).
However, I suggest to rename it `template_for_committee_id`, so it is easier to pass and receive this field to and from the backend.
So, if you agree with me, then please update the actions to match the description in the wiki:
- [x] [meeting.create](https://github.com/OpenSlides/OpenSlides/wiki/meeting.create)
- [x] [meeting.update](https://github.com/OpenSlides/OpenSlides/wiki/meeting.update)

**Comment by jsangmeister** [comment]
I would argue to keep it as a boolean flag since otherwise we introduce a new possibility of data inconsistency (if `template_for_committee_id` is not the same as `committee_id`) and therefore need for validation. Receiving the field is independent from the payload and passing the field should be pretty simple since it's just a boolean.

**Comment by GabrielInTheWorld** [comment]
This is okay for me. I have updated the wiki accordingly.

**Comment by jsangmeister** [comment]
As discussed @r-peschke: We are moving the template relation from the committee to the organization. Since there are no template meetings yet, we can just ignore the old field and don't need to write a migration for that.
