### ISSUE TITLE
Meeting clone error: "mediafile/1: is_public is wrong. True != None"

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-backend#1215]
Error after meeting clone:
` Error: mediafile/1: is_public is wrong. True != None`

**Comment by jsangmeister** [comment]
Probably the same error as in https://github.com/OpenSlides/openslides-backend/issues/1182. Can you provide the datastore content? (maybe ask @GabrielInTheWorld for help)

We could think about implementing an `export` presenter which outputs the same json which is used for cloning. This can be implemented quickly since the functionality is already there and might ease the communication for these kind of debugging issues.

**Comment by r-peschke** [comment]
The error can be reproduced easily by setting the is_public field of a mediafile to None or don't set is_public at all in test.
The checker recognize this in check_calculated_fields and reports the mentioned error.
The import uses the same checker, i.e. we can be sure, that the data was correctly imported => look for it

If it is not the import, how is the value destroyed?
