### ISSUE TITLE
Document migration HTTP routes

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#1227]
The migration command "progress" is not mentioned in the migrate.py but this command can be called via HTTP route. It would be nice if someone can cleanup this either by extending the migrate.py script and/or moving some logic from the HTTP route code to another layer.

**Comment by normanjaeckel** [comment]
Because the migrations should be run from the manage tool in future it would aslo be ok for if you remove the migrate.py script completly and move all necessary logic to the HTTP route code.

**Comment by jsangmeister** [comment]
The `progress` command is not in the migrate script since it is a backend-only feature. The migration is run inside a thread and the progress is gathered and reported.

Removing the `migrate.py` would also be fine for me, but I think this removes some flexibility and, more importantly, would require a lot of restructuring which I don't think is worth the work nor provides much benefit.

**Comment by normanjaeckel** [comment]
Ok, then please add a README or something where one can see the HTTP interface (possible commands and flags and the respective responses). It was not easy for me to see everything at a glance by reviewing some lines of code.
