### ISSUE TITLE
Implement the relation between organization and users

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1237]
Currently, the only way to get every user in an organization is to use the presenter (`get_users`). This will no longer be sufficient for the client. Therefore, implement the relation between organization and users, so the client can get autoupdates for this.

**Comment by jsangmeister** [comment]
We explicitly did not do this since this relation will get HUGE and will blow up the space used by the event store. If this contains 1 million users, the event store contains an event for every update which was done. This means the update events use quadratic space (O(n²)) just for this relation alone, which would result in something the size of 1 billion (!) integer values being stored in the event store just for this relation alone. Clearly, this is not feasible.

On the other hand, for what do you need this relation? Disregarding the space issues, it is not feasible to display such a huge amount of users in the client. That's the whole reason we introduced the `get_users` presenter, so the client can paginate the user list view and not be overwhelmed by too much data. If you need autoupdates for the users, you can just request them "manually" for all users on the current page returned by the presenter.

**Comment by GabrielInTheWorld** [comment]
Yeah, this sounds big. I talked to @r-peschke and @reiterl, yesterday. They seemed confident, that we can implement this relation, without such an effort, you talk about.

The explicit use case is, that we have an account list which should display every user in an organization. However, if there are updates to the list (for example, a username was changed or a user was deleted), the list won't be automatically updated.
The client could "automatically" get updates by polling the presenter every minute or so, but this brings in my opinion other disadvantages.

Besides, there is currently no database with an amount of over 1000 users. I think, we should implement this relation and investigate, how much storage space it takes. But this is my opinion.
What do you think (@jsangmeister, @r-peschke, @reiterl, @emanuelschuetze)?

**Comment by jsangmeister** [comment]
As discussed: The size fo this relation would probably be too much for the event store, but, more importantly, for the client, which cannot load and display 100.000+ users in one request. The presenter `get_users` suffices for this and supports filtering and pagination, which is required to handle this amount of data. For the results from the presenter, automatic updates can be requested if needed, but for e.g. selecting a specific user to add to a committee, this should not even be necessary.
