### ISSUE TITLE
Don't show datastore errors to client

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#1262]
If an exception happens in the datastore-writer, then the client gets a response with status code 400 with the content of the response from the datastore to the backend:

```
"Bad response from datastore service. Body does not contain valid JSON. Received: b'<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\\n<title>500 Internal Server Error</title>\\n<h1>Internal Server Error</h1>\\n<p><img src=\"[https://http.cat/500]()\"></img></p>\\n'"
```

Instead, the backend should return statuscode 500 to the client and not show the any internal content from the datastore.

You can reproduce this, by raising an excpetion in the datastore.

**Comment by jsangmeister** [comment]
It's ok for me to not show the internal information to the client, but I don't agree with sending response code 500: Datastore exceptions can have a multitude of reasons, e.g. that a model simply does not exist (which is definitely a 4xx status code since the user requested an invalid action). So to summarize: Remove datastore output from error and log it instead. The status code handling should stay the same as before.

**Comment by ostcar** [comment]
A 400er should be send if the request from the client is wrong and the client has to do something different. A 500er should be send if the server code is wrong and the user can not do anything about it.

It should be possible for the backend to distinguish between this two cases.

**Comment by jsangmeister** [comment]
> A 400er should be send if the request from the client is wrong and the client has to do something different. A 500er should be send if the server code is wrong and the user can not do anything about it.
> 
> It should be possible for the backend to distinguish between this two cases.

Not necessarily. If the datastore returns a `ModelDoesNotExist`, it may be because the user sent an invalid action for a not existing model or because the backend has an error and requested the wrong model from the datastore. But the assumption is always that the code is correct, so a 400er is returned.

On the other hand, if the datastore returns a 500, then the situation is clear and the backend should also return a 500.
