### ISSUE TITLE
motion_change_recommendation.create strange behavior with the collide code

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-backend#1279]
I think the collide code is incorrect.
Two **closed** intervals are disjunct, iff they don't "touch" each other.
eg. 1-5 and 5-10 are not disjunct.
and 5-10 and 1-5 are also **NOT** disjunct.
If I look at the tests: `test_create_change_recommendation_min_overlap_1` and `test_create_change_recommendation_min_overlap_2`,
I am confused.

**Comment by jsangmeister** [comment]
Although I did not find any documentation whatsoever about it, it seems that `line_to` is __exclusive__, so the previous documentation in the wiki (https://github.com/OpenSlides/OpenSlides/wiki/motion_change_recommendation.create) was correct in that sense. See also https://github.com/OpenSlides/openslides-backend/issues/513 where this was initially implemented.

That being said, I don't think it makes any sense at all and it is correct to change this so both values are inclusive. But I don't have enough overview of the client and the diff algorithm to know if this will create much overhead. Maybe @GabrielInTheWorld or @CatoTH can chime in here and hopefully confirm that it would not be that much work.

On another note, the min_overlap tests as well as the exists query seem very confusing to me as well. So either we are not understanding it correctly now or when implementing it, me and the reviewers all overlooked that it didn't make sense...

**Comment by jsangmeister** [comment]
Talked with @emanuelschuetze and @reiterl and we want to make `line_to` inclusive to avoid future confusion. This requires a migration besides the changes already present in this PR. The migration should decrement `line_to` for all change recommendations where `line_to > line_from`. The `>` is especially important since title change recommendations have `line_from == line_to == 0` (which is also not document, I will do that now).
