### ISSUE TITLE
Permission Service

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#13]
The backend should have a PermChanger-Service that listens to changed keys and send other keys that also could have changed.

The PermChanger has to listen on changed keys. See https://github.com/OpenSlides/openslides-datastore-service/issues/5

This has to be done in a redis consumer group. This means, that when many permchanger-services are started, each event in the stream should only been read from one service. Therefore the redis command [XREADGROUP](https://redis.io/commands/xreadgroup) has to be used.

After the changed keys are processed, all possible changed keys for a list of users have to be send to a different redis stream. I am not sure what the best format is. It could be:

`xadd perm_changed * updated '{"uid":[1,2,3,4],"keys":["foo", "bar"]}'`

Please tell be when you have any suggestions and when you have a first implementation to test.

**Comment by FinnStutzenstein** [comment]
Quick note regarding the renaming: The permission service is resposible for detecting, aggregating and publishing events for changed permissions, because of the similar logic required.

Regarding calculation of changed fields: This is stateless, so it is possible to do it in a consumer group (as Oskar wrote).

@ostcar Please do an interface specification for your needs in the `openslides4-dev` branch in the master repo. There you can specify the events in a common manner.

We do not plan to implement this as soon as possible. The current goal is to use OS as the superadmin, so even if the superadmin changed permissions, these won't affect the superadmin. This means, that all services, that needs the permission service (the change-events or calls to it) can stub it easily. For events, just do not generate any events in the stub and for calls for permissions, just return, that the user is authenticated.

**Comment by normanjaeckel** [comment]
@ostcar Can this be closed?
