### ISSUE TITLE
Meeting.import creates duplicate users

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1429]
See OpenSlides/openslides-client#1415

There have been reports that, when one imports a meeting there are new users created for every entry. If there was already a user by that name a number will be used to distinguish between them, essentially creating duplicate users.

The expected behaviour (based on how it is in the client) is that existing users with that name will be searched for and, if they exist, they will be referenced. User creation should only be used in cases of unknown names to avoid having hundreds of duplicates.

The bug description in the client was very OS3 specific, so maybe this just happens with OS3 export files.

**Comment by reiterl** [comment]
At meeting import a new user will be create, if no user with same `username`, `first_name`, `last_name` and `email` exists.
As username must be unique, it gets a trailing number.

**Comment by luisa-beerboom** [comment]
> At meeting import a new user will be create, if no user with same `username`, `first_name`, `last_name` and `email` exists. As username must be unique, it gets a trailing number.

Is that what currently happens? If so, you should talk to @MSoeb to get to know the specific problem

**Comment by jsangmeister** [comment]
@MSoeb can you provide more specific details here?

**Comment by r-peschke** [comment]
The reason for the error: If a username from import was not found in Database or the other fields (email, first and last-name) doesn't match, OS4 uses the method to implement the new username-policy (UsernameMixin.generate_usernames), which guarantees the uniqueness of the username and removes all Blanks from the name.

@emanuelschuetze @rrenkert 
Because all imports up to now imported the usernames after applying the OS4-username-poliy (=remove ALL spaces from existing usernames), we should continue doing it this way, but we also have to search in database with the applied OS4-username.
