### ISSUE TITLE
Discussion: Relocate csv imports to the backend

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1436]
According to a quick search through the client files, currently the client handles the following imports itself: 

- [ ] Topic-import, see #1661 
- [ ] Motion-import
- [ ] Committee-import
- [ ] Account-import (Organization-level user data)
- [ ] Participant-import (Add users to a meeting)
- [ ] Statute-paragraph-import (Something with motion statute paragraphs)

Meanwhile that meeting-import is already handled by the backend.

During multiple conversations during the past few weeks, a general will to eventually move these imports to the backend has been commonly voiced.

We should make plans on how to do this in a standardized and maintainable manner.

This issue is the place to collect various ideas and plans concerning that.

**Comment by luisa-beerboom** [comment]
Concerning this, from the client point of view an interesting question would be:

The client currently shows previews for its various imports, these show what will be created, what referenced, and what ignored. In the aftermath this preview will/should also (in theory) show which/how many actions succeeded or failed (and why). We should probably consider how we will handle that when the import itself is done by the backend.

Could we perhaps handle it in such a way where the client sends the import file and the actual import request separately? I.e. maybe:
1. Client sends the import file with a reference to what type of import it's supposed to be
2. Backend temporarily saves the file and creates a preview which will be sent to the client
3. Client either sends the actual import action or an abort action.
4. Backend carries out the import and returns the result

**Comment by jsangmeister** [comment]
Temporarily saving the file is not as easy because the backend is scaled and the next request might not land at the same backend. My proposal would be to implement the actual code once and import it into an action and a presenter. First, the presenter is called by the client and returns the data that would be imported by the action. Then, the client can call the action with the same payload and execute the actual import. This might lead to slight differences if some data is changed between the presenter and the action call, but this is also currently the case with the full-client approach and would also be very hard to solve with your approach: If e.g. the import would create a user "A" and between creating the preview and executing the import, a user "A" is created by someone else, what should happen? Either the backend silently ignores it and just updates the user, which would be the same behaviour as now, or it throws an error that some data was changed, which is not very UX-friendly, since it might lead to the user having to re-import the data multiple times before no conflict exists.

**Comment by luisa-beerboom** [comment]
So a presenter that returns the preview and then the actual import action is a separate matter entirely?
That's fine by me as well.

**Comment by jsangmeister** [comment]
> So a presenter that returns the preview and then the actual import action is a separate matter entirely? That's fine by me as well.

Yes, from a client POV that's correct.
