### ISSUE TITLE
Introduce a relation between organization.user_ids and user.organization_id

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1439]
The autoupdate-service needs this relation to detect new users in a subscription of an organization-wide user list

To do:
- change models.yml
- action user.create: fill organization_id
- migration: initiate fields

**Comment by jsangmeister** [comment]
This was already discussed several times and we decided every time against it for performance reasons: This relation will get HUGE and get changed very often, therefore requiring a) a lot of autoupdates with a huge amoount of data (the list itself) which doesn't change much and b) a lot storage space and events in the datastore. The solution for this was the `get_users` presenter, which paginates the user list so that the client can request autoupdates for only a small subset of users.

**Comment by jsangmeister** [comment]
After talking with @r-peschke, this is okay for now as long as the user numbers are comparatively low.

**Comment by ostcar** [comment]
Really? So we don't have the goal anymore to support 100.000 users anymore?

Or is there a reason why we only need a solution for now and not for the long run?

**Comment by r-peschke** [comment]
> Really? So we don't have the goal anymore to support 100.000 users anymore?

This is the standard way of the current design for lists with autoupdate functionality. IMO implementing various ways of handling different cases will complicate developing the solution at all. 
> 
> Or is there a reason why we only need a solution for now and not for the long run?

My opinion: we have to change a lot in our (database)-design, amongst others in answer to new requirements of OS4.

**Comment by reiterl** [comment]
Should user/organization_id be required? This leads to a lot of test failures.

**Comment by jsangmeister** [comment]
> Should user/organization_id be required? This leads to a lot of test failures.

Yes. Best to find a central place (probably `base.py`) to introduce the field

**Comment by r-peschke** [comment]
user/organization should be required and both fields should have restriction mode A

**Comment by ostcar** [comment]
For the performance of the autoupdate-service it would be better to be more restrictive. 

The field `organization/1/user_ids` will contain a very long list of user_ids. So each time the field gets fetched or updated (with the current implementation this is very often), the restricter has to go though all of the user ids and check, if the requesting user can see it. 

For this reason it would be better, that to see the field `organization/1/user_ids` the user has to have the permission to see `all` users. This is only true for users that have the OML can_manage_users or higher. In this case the field could be returned without going though all of the ids.

I do not think this will be a problem for our use case since the account list is only needed for user-managers.

Therefore I propose a new restriction mode for the organization that is only visible when the user has the OML can_manage_users or higher.

The effect will be, that you need this permission to see user/1/organization_id. The reason is, that to see a relation field, you also need the permission to see the related field. So you can put the field `user/organization_id` in restriction mode F.

**Comment by ostcar** [comment]
> > For the performance of the autoupdate-service it would be better to be more restrictive.
> > The field `organization/1/user_ids` will contain a very long list of user_ids. So each time the field gets fetched or updated (with the current implementation this is very often), the restricter has to go though all of the user ids and check, if the requesting user can see
> > Why do you think this list will update often? It's only updated by creating or deleting a user!
> > IMO updating the content of the user is working with the help of a presenter.
> > For this reason it would be better, that to see the field `organization/1/user_ids` the user has to have the permission to see `all` users. This is only true for users that have the OML can_manage_users or higher. In this case the field could be returned without going though all of the ids.
> > I do not think this will be a problem for our use case since the account list is only needed for user-managers.
> 
> I'm not sure about this! The meeting admin is allowed to select any user by some search-criteria to invite him to the meeting.
How is this currently implemented? The meeting admin of a meeting is currently not allowed to see all users.

> > The effect will be, that you need this permission to see user/1/organization_id. The reason is, that to see a relation field, you also need the permission to see the related field. So you can put the field `user/organization_id` in restriction mode F.
> 
> I don't understand this part. Nobody needs the user.organization_if field, it's always 1.
That is true. But you still have to put it in a restriction mode. So please use restriction mode F.
