### ISSUE TITLE
Forwarding fails in the source committee, if there is already an account with the exact username of the source committee

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-backend#1441]
### Description of the problem

- After a motion is forwarded, a message is displayed stating that the motion has been successfully forwarded to the target conference. But this motion does not appear in the target conference.
- A failed forwarding can be recognized by the fact that in a motion below the field "Creation date" the field "Motion forwarded to" is not visible.

### How to reproduce & Example

→ testintern → /86/motions/1

"Source Conference A" = Committee title = Event title
"Target Conference B" = Committee title = Event title

Motion from "Source Conference A" → "Target Conference B"

When forwarding a motion, an account is automatically created with the username of the committee from whose event the motion is to be forwarded. In my example, this is "Source Conference A". The motion will then (normally) end up at "Target Conference B". The submitter:in is then "Source Conference A".

However, if someone in the "Source Conference A" have already manually created an account with the exact name "Source conference A", so that this account is listed in the motion as the submitter, then the forwarding will fail. Because: By creating this account manually, there is already an account with exactly this name ("Source Conference A"). Therefore, no account can be created during the forwarding process. 

### Weiteres ToDo

- [ ] Revise notification message while/after forwarding. Only display "Motion successfully forwarded" if this is actually the case. Otherwise, display an error message with the reason for the failed forwarding.

**Comment by r-peschke** [comment]
This doesn't work, because the backend looks for a registered user to replace the motion-applicant in the forwarded motion. If there is no user registered, it tries to create with **the name of the committee**. This fails, if the username is used, because it has to be unique. There is a bug in the client, that the error message is not shown, but instead the success message => see https://github.com/OpenSlides/openslides-client/issues/1530.

We should search for a solution and take account of:
1. the created user is a system user, set inactive and no physical user, but with the default group of the selected meeting. Forwarding to other meetings will automatically add their default group to the user.
2. Not all of the openslides customers will want the real motion-applicant automatically replaced by a committee_named user
3. To set the motion-applicant user manually is a lot of work and the name of the real petitioner at the original meeting gets lost

IMO from 1. results we shouldn't capture a user with an accidental same username as the committee without being registered as forwarding user of this committee. This will be a user with growing rights for all meetings forwardings will be made.
If the customer is not sure about the behavior of openslides and creates a special user for this use case, creating another user with a generated unique username and replace the wanted user is also a bad solution.

Proposal 1: The customer has to create a user, if he wants this behavior, he sets the user as forwarding_user for one or more committees. The customer should be aware of the growing rights and may set this user inactive/not physical. On forwarding a motion we look in the source committee for a forwarding user. If we find one, we will use it for the forwarded motion in the target meeting, otherwise, fulfilling point 2, we will use the original user in the target meeting. Disadvantage and advantage: The forwarding user has to be set for each committee
Proposal 2: If the username exists, we could create a user with a different name, for instance the committee-name with a serial number appended. To fulfill point 2 we introduce a flag on organisation-level. Additionally we inform the customer that there is no need to use the committee name user as motion-applicant, it will be replaced automatically.

@alveolus @emanuelschuetze  @rrenkert @luisa-beerboom

**Comment by luisa-beerboom** [comment]
Proposal 3: We change the code to not use the committee name as the user name for the system user:

We'll create a system that always generates a unique username for that user (perhaps something like forwarderCommittee<committee_id>-<some salad of letters>) and writes the committee title into another field that determines the full name (like `last_name`).

i.e.
username: "forwarderCommittee23-w34tei8r"
last_name: "Finance Committee"

Since the client doesn't show usernames anywhere but the detail-view, the above user would always be displayed as "Finance Committee".
That the username is a bit hard to remember doesn't really matter either, because the system user will be set inactive anyway, and if the administrators want to set him active and are unhappy with the name, they can just manually change that name to whatever they see fit, right alongside that.

**Comment by jsangmeister** [comment]
Yes, manual setting of the user is a bad idea and complicated for the admins. Just using the default username generation should be enough, appending some number to the committee until it doesn't exist yet.
