### ISSUE TITLE
Remove user projection code

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1600]
The ability to project users has long since been removed from the client, why not remove it from the backend as well?

There are still a couple of fields that technically make the user model projectable:

`projection/content_object_id` (allows a user to be chosen)
`user/projection_$_ids`

`meeting/default_projector_$_id` (`user` can be selected)

Since this issue involves template fields, it should probably wait for the template field removal.

**Comment by jsangmeister** [comment]
@r-peschke what infos would you like?

@luisa-beerboom I don't think this has to wait for template field removal, since the fields itself aren't touched, only the defined replacements in the models file and probably some tests regarding these. It should be easy to remove and to automatically merge these changes in the feature branch.

We should not write a migration for this, even though we will keep deprecated data around.

**Comment by jsangmeister** [comment]
Clarification:

The ability to project users has been removed from the client and should be removed from the backend as well.
Things to do for this:

- `user/projection_$_ids` should be removed
- the replacement `user` should be removed from `projection/content_object_id`
- the replacement `user` should be removed from `meeting/default_projector_$_id`

Naturally, all tests and code, if existing, can be removed as well.

@r-peschke @reiterl clear enough or do you need more infos?

**Comment by reiterl** [comment]
It seems clear for me, I will do it now.

**Comment by reiterl** [comment]
Also remove the replacement `user` from  `used_as_default_$_in_meeting_id`.
