### ISSUE TITLE
organization.update users_email_replyto accepting invalid email addresses

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-backend#1613]
The field `users_email_replyto` within `organization`s is accepting invalid email addresses resulting in errors when trying to send emails. 

Original issue: https://github.com/OpenSlides/openslides-client/issues/1969

**Comment by reiterl** [comment]
How do you want us to solve this issue? There is nothing like an email field in the backend. I don't think that this is a *bug*.

**Comment by jsangmeister** [comment]
The fields `organization/users_email_replyto`, `meeting/users_email_replyto` and `user/email` should be validated by some kind of email validator (pick your favourite). Also, leading and trailing spaces should be trimmed from the address before saving it.

Maybe this could even be added as its own type into the `models.yml`, so it can be directly checked by the schema, but I guess that's overkill since it requires changes in multiple other services which use the models file.

**Comment by r-peschke** [comment]
In action/mixins/send_email_mixin.py you'll find a class EmailMixin with a staticmethod check_email, that will do the job.
