### ISSUE TITLE
[imports] Relocate csv imports to the backend: account (user import independent of meeting) 

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1688]
Details see in actions https://github.com/OpenSlides/OpenSlides/wiki/without_templ.account.json_upload and https://github.com/OpenSlides/OpenSlides/wiki/without_templ.account.import.

For building username and default_password use the methods of user.create/update.

@emanuelschuetze @MSoeb  @rrenkert @jsangmeister @luisa-beerboom see specification of actions(links above) and let's discuss or give your okay for the factual requirements.

**Comment by luisa-beerboom** [comment]
Two questions:
1. What will happen if I try to import a user without specifying a username but with a first and last name which already exist? Will he be created, updated or skipped?
2. In the client csv-imports it is currently possible to use `0` as `false` and `1` as `true` as input values for boolean fields, if I were to translate it into boolean accurately, I'd have to know that the column is supposed to be a boolean column (On further inspection the same problem may occur with number columns). Should the client translate these things (even if that means knowing the type of the columns) or should the backend just accept the raw values and translate them itself?

**Comment by jsangmeister** [comment]
The recent rework of the `search_users` presenter enforced the following rules, which I think we should follow here as well:
- if a username is given, the user is matched by that and only that. This means that one could even change data like first name, last name, etc. if a username is given and matches.
- if no username is given, the user is tried to be matched by first name, last name and email. If all three match, the user will be counted as a duplicate, if less match, a new user is created.

We could discuss what should happen if all 4 fields are given. Currently, the behaviour is that if the username is given, all other fields are ignored, but I'm open to changing that. This would mean that one could match a user via first name, last name and email and update his username. On the other hand, this could lead to unwanted user updates and frustation if the user then cannot log in again, which is why we did not implement it this way.

I'm against letting users configure this because it will be overly complex and used by only very few power users. Giving a strict ruling to which all users must abide is the better way, I think.

**Comment by jsangmeister** [comment]
> there is an object with info [...] "updated", if the username was extended to be unique.

This can never happen, because if the username needs to be extended, that means the data matched some user by username and should therefore reference it instead of a new user being created.

**Comment by r-peschke** [comment]
> The recent rework of the `search_users` presenter enforced the following rules, which I think we should follow here as well:
> 
>     * if a username is given, the user is matched by that and only that. This means that one could even change data like first name, last name, etc. if a username is given and matches.
> 
>     * if no username is given, the user is tried to be matched by first name, last name and email. If all three match, the user will be counted as a duplicate, if less match, a new user is created.
> 
> 
> We could discuss what should happen if all 4 fields are given. Currently, the behaviour is that if the username is given, all other fields are ignored, but I'm open to changing that. This would mean that one could match a user via first name, last name and email and update his username. On the other hand, this could lead to unwanted user updates and frustation if the user then cannot log in again, which is why we did not implement it this way.
> 
> I'm against letting users configure this because it will be overly complex and used by only very few power users. Giving a strict ruling to which all users must abide is the better way, I think.

IMO we should give a general option to configure. For centralized organizations with a central LDAP the unique username is sufficient. Locally organized they should match on 3 or 4 fields for secuity reasons.

**Comment by rrenkert** [comment]
We follow the current implementation of the ```search-user``` presenter which was already described by @jsangmeister. In case all 4 fields are given, the username is the leading criteria to match. This way we allow an update of e.g. the last name.

Nevertheless we should describe the rules for user matching in the import dialog and advice the user that performs the import to carefully review the preview before starting the real import.

**Comment by reiterl** [comment]
I cannot continue here, because there is a conflict of the description here and the wiki and I miss some information in the wiki. (e.g. created, timestamp, possible status, etc.)

**Comment by reiterl** [comment]
Do we also check the data for duplicates? Or only do a lookup in the database?

**Comment by jsangmeister** [comment]
Yes, the data must also be checked
