### ISSUE TITLE
[imports] Relocate csv imports to the backend: Motion

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1713]
Action description still needed.

**Comment by luisa-beerboom** [comment]
I took a look at how it is done in the client:
The current client import uses the following string properties:

```
title => required
text => required
number
reason
submitters => reference to foreign model: user (if empty: user that called the action should be used)
supporter_users => reference to foreign model: user
category => reference to foreign model: motion_category
tags => reference to foreign model: tag
block => reference to foreign model: motion_block
```

`submitters`, `supporter_users` and `tags` are lists.

If the text value isn't surrounded by html tags, the client currently adds `<p></p>` tags around it, which should be taken over by the backend.

It looks like duplicate checks are done via the `number` property. So there ought to be an error if one motion number is present multiple times.

When it comes to the object references, tags and motion_blocks should be quite easily created.
Categories are exported by the client as `<prefix> - <name>`, therefore the backend would have to split the category by " - " before searching.

The problem comes with the two user properties:
The users are currently exported by the client as `<title> <first_name> <last_name> (<pronoun> · <structure_level> · <number>)`.
The backend would either have to be programmed to extract the relevant data from this type of sting, or we'd have to add a requirement to the client issue that the motion export removes the things, the backend can't handle.

Also there I have questions concerning what to do with user searching.
The client currently, as far as I can tell, searches among the meeting's participants and if it doesn't find the user, I think it creates him anew.
We may want to discuss if we want to do things differently in the backend. Obviously this is partially a permission issue, if we allow creating users, someone without `user.can_manage` should probably receive row errors/warnings if there is a user that doesn't exist yet. Adding pre-existing accounts to the meeting may be possible as well. On the other hand, we could consider requiring all referenced users to already be part of the meeting and skipping those that aren't or smth.

@rrenkert @r-peschke What do you think the requirements should be?

**Comment by r-peschke** [comment]
@rrenkert  @MSoeb

After discussion with @luisa-beerboom and @r-peschke:
Questions:

-  motion create and update (via number to identify)?
- search users: use always only the `login-username`. We could create a second motion.export in client with login-username only. The existing export exports a **long** username. Otherwise we have to change existing motion.export. Which way to go?
-  What's about supporter or submitter-users, which are not part of the meeting, but exist in organization? Refuse them or add them to the meeting depending the permission of the importing user?
- Warnings or errors on all cases of found/not found users?
- How to look up motion-category? Client side export of motion write motion-category as `prefix`- `name`, name is required. Proposal: Looking for uniqueness in meeting, split string by " - " and search for both, if there are 2 parts, otherwise name and empty prefix. 

Prerequisites:
Uniqueness for collection fields except user allows means inside of a  meeting

**Comment by rrenkert** [comment]
> @rrenkert @MSoeb
> 
> After discussion with @luisa-beerboom and @r-peschke: Questions:
> 
> * motion create and update (via number to identify)?

Yes, I think update with number as identifier is ok.

> * search users: use always only the `login-username`. We could create a second motion.export in client with login-username only. The existing export exports a **long** username. Otherwise we have to change existing motion.export. Which way to go?

We should extend the current export to include the username as columns. Keeping the the current user may be useful for other applications besides an (re-)import.

> * What's about supporter or submitter-users, which are not part of the meeting, but exist in organization? Refuse them or add them to the meeting depending the permission of the importing user?

Do they have to belong to the meeting? In other parts (list of speakers) we keep users that are not part of the meeting.

> * Warnings or errors on all cases of found/not found users?

Warnings please. :)

> * How to look up motion-category? Client side export of motion write motion-category as `prefix`- `name`, name is required. Proposal: Looking for uniqueness in meeting, split string by " - " and search for both, if there are 2 parts, otherwise name and empty prefix.
> 

We need two columns to identify the category. the prefix can contain all chars including "-".

**Comment by luisa-beerboom** [comment]
> > * What's about supporter or submitter-users, which are not part of the meeting, but exist in organization? Refuse them or add them to the meeting depending the permission of the importing user?
> 
> Do they have to belong to the meeting? In other parts (list of speakers) we keep users that are not part of the meeting.

@rrenkert 
It would maybe be _possible,_ but would it be _sensible?_
Why should a user be set as the author/supporter of a new motion when he quite possibly has never been part of the meeting and would have neither right nor reason to submit or support anything?

**Comment by jsangmeister** [comment]
I agree with @luisa-beerboom on this, e.g., when setting the supporters/submitters manually, we prevent such a thing from happening. The same should be true with imports.

Actually, thinking about it, the `equal_fields` defined [here](https://github.com/OpenSlides/openslides-backend/blob/732341a1c8f0f52170c4d8f878638a2ab497cb5b/global/meta/models.yml#L2350) should prevent users which are not part of the motion's meeting from being added, anyway.

**Comment by r-peschke** [comment]
In json-upload we have to use all the code checks from the actions used in import, i.e. motion.create, motion.update including used mixins. All checks and the errors must be reported in json-upload at the same error or warning level as in the original check. The checks have to be reorganized in a way to be accessed from the original action and the json upload.

Further details see in [motion.json_upload](https://github.com/OpenSlides/OpenSlides/wiki/motion.json_upload)- and [motion.import](https://github.com/OpenSlides/OpenSlides/wiki/motion.import)-action
