### ISSUE TITLE
Issue with participant deletion

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-backend#1792]
**Description:** When an participant is deleted from an active meeting, he or she is also incorrectly deleted from an archived meeting in which he or she participated. With this deletion, all references to the participant disappear in the archived meeting and in the account list.  

**Reproduction:**
Precondition: Two meetings are needed. One is archived.  Participant list on both meetings should include at least one identical account. 
1. Open active meeting
2. go to Participants > delete the user who is part of the archived meeting
3. open archived meeting and check the participant list. 

**What should happen:**
If a user is part in an archived meeting, the deletion should only takes part in the active meeting, where he or she is deleted from and not global. The deletion rule for archived meeting should be the same like for active meetings.

**Comment by r-peschke** [comment]
> **Description:** When an participant is deleted from an active meeting, he or she is also incorrectly deleted from an archived meeting in which he or she participated. With this deletion, all references to the participant disappear in the archived meeting and in the account list.
> 

The **realized** use case for the **client dialog** is the following: 
- The user manager of the meeting wants to remove the user, because the user told him he will leave it forever
- The user manager doesn't know whether the user leaves just this meeting or the whole organization. The intention of the dialog is to delete the user at all, if he isn't active anymore in the organization. This way we try to avoid nominal users (Karteileichen). But if the user is still **active** in an other meeting or is manager of a committee or at organization level, he will just be removed from the meeting (technically removed from all groups of the meeting).
- The decision what to do, is taken by the client only. Depending the decision the client calls `user.delete` or, I assume, `user.update` for removing the user from all groups of the meeting.

Annotation: With #1426 it is planned to move this decision to the backend.

> **Reproduction:** Precondition: Two meetings are needed. One is archived. Participant list on both meetings should include at least one identical account.
> 
>     1. Open active meeting
> 
>     2. go to Participants > delete the user who is part of the archived meeting
> 
>     3. open archived meeting and check the participant list.
> 
> 
> **What should happen:** If a user is part in an archived meeting, the deletion should only takes part in the active meeting, where he or she is deleted from and not global. The deletion rule for archived meeting should be the same like for active meetings.

Different solutions:
1. For just removing the user from this meeting, we have to remove the user from all groups in this meeting
    - disadvantage: we will keep with nominal users (Karteileichen), even knowing, that the user has gone
2. We could change the rules for the decision, the client takes. May be this is not that easy, because now the user scope is taken as base and the presenter **get_user_related_models** is not capable, see #1795.
3. We could present 2 buttons and let the user take the decision: **delete user** or **remove user from meeting**
4. Changing the `user scope calculation` and including archived meetings
   - disadvantage 1: If the requesting user has sufficient committee- or organization-level rights, the result is the same
   - disadvantage 2: If the organization uses the `meeting archive` feature, a lot of changes of user data will require committee- or organization-level rights for the requesting user.
5. We could realize the #1426, but still have to decide the rules
6. We could think about a `series` of meeting, for example the monthly meetings and giving rights to the meeting admin to all meetings of _his_ series. This may be a great effort, because it would behave like a new structure level between committee and meeting 

I'm sure there are more ideas.-)
We shouldn't forget, that the user scope is the essential concept for the permission handling of changes on user data.

Opinion and/or decisions please: @emanuelschuetze @MSoeb @rrenkert @jsangmeister @luisa-beerboom

**Comment by rrenkert** [comment]
Talked to @emanuelschuetze and @MSoeb:
To have this problem fixed we prefer item number 2.
5. takes too much time to define all the rules and edge cases at the moment but for the long term we should keep this in mind.

**Comment by jsangmeister** [comment]
What should the new rules for the client be? #1793 is then obsolete, I guess?

**Comment by jsangmeister** [comment]
Talked with @rrenkert and @r-peschke: The client requests the user scope. If that is `organization` or `committee`, the user cannot be deleted anyway and is only removed from the meeting. If the scope is `meeting`, the `get_user_related_models` presenter is requested. That presenter will be changed so that all meetings are included, see https://github.com/OpenSlides/openslides-backend/issues/1795. The client then checks if the user is in other meetings than the active one and only removes the user from the meeting instead of deleting it, if that's the case.
