### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#184]
How can we speed up the tests? At the moment GitHub Actions runs the tests by creating a lot of docker containers e. g. for the datastore. Can we use some caching here?

See https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei

Who is interested in solving this?

**Comment by jsangmeister** [comment]
For the datastore, I tried to find a solution for caching some things for speeding up travis at that time, but didn't find an easy solution. So while I'm fully on your side that this is a good idea, I don't think we should do it right now, since we have enough other work to do. I would suggest to at least move it to after the next milestone. But if you want, feel free to try it.

**Comment by FinnStutzenstein** [comment]
The best way for the DS would be using a repository and doing a CD in the datastore repo to update the image on every merge. But this needs to be set up...

**Comment by normanjaeckel** [comment]
@ostcar Do you like to "grübel" about this?

**Comment by ostcar** [comment]
You could learn from the best

https://github.blog/2020-10-29-making-github-ci-workflow-3x-faster/

**Comment by jsangmeister** [comment]
Finally came to reading the article. That's not really what we want though, right? I would have a bad feeling if we could merge changes without them being checked first. The way to go would be to cache part of the docker images, but someone would have to read into how to do that.
