### ISSUE TITLE
Wiki entries for account/user import actions have different titles from code

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1879]
The wiki entry for the account import names the action as `account.json_upload`, the actual name used in the service, however, is `user.json_upload`. It's the same for the import actions.

This has been an inconvenience when developing the client-side of this.

Please either correct the wiki entry or the backend to make everything match.

**Comment by jsangmeister** [comment]
The wiki is already updated since https://github.com/OpenSlides/openslides-backend/pull/1820 renames these imports, because we will then have an account import and an participant import. This is standard procedure with backend changes, but I agree that it can cause confusion during the process, especially if it takes a longer time. Unfortunately, the wiki does not allow feature branches or the like, so we are stuck with this.
