### ISSUE TITLE
Fix amendmend_paragraph in motion.update

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#226]
https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/action/motion/update.py#L24

This line has to be removed. The question is where the client wants to add and update amendment_paragraphs.

**Comment by jsangmeister** [comment]
@reiterl you can do this. See https://github.com/OpenSlides-action-crew/openslides-backend-coordination/issues/25#issuecomment-712123798

You will have to validate the fields manually, since AFAIK jsonschema doesn't offer this kind of dynamic key validation. Try to find a generic solution for it since we will probably need it in more places. If you have questions about this, just ask

**Comment by normanjaeckel** [comment]
Or we switch to a more explicit payload as asked here: https://github.com/OpenSlides-action-crew/openslides-backend-coordination/issues/25#issuecomment-712409354

**Comment by jsangmeister** [comment]
Will take care of this.

**Comment by jsangmeister** [comment]
Done in https://github.com/OpenSlides/openslides-backend/pull/273/
