### ISSUE TITLE
update to the ```get_forwarding_meetings``` presenter

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-backend#2356]
see for context https://github.com/OpenSlides/openslides-client/issues/3429

> This will require an update to the get_forwarding_meetings presenter as it currently returns only the meetings which can be forwarded to.

Please update the presenter in a way that the correct committees can be displayed

**Comment by peb-adr** [comment]
Alternatively implement this as a new presenter instead of extending the existing one.

**Comment by jsangmeister** [comment]
What this presenter should return is basically the relation `committee/receive_forwardings_from_committee_ids`. If we change the restriction mode of this relation, the client can simply access this relation instead of calling a presenter. Since the dropdown in the client is visible if the user has `motion.can_manage`, I would suggest to implement a new restriction mode `C` for committees which says: "The user must have the permission `motion.can_manage` in at least one meeting of the committee". I would favor this solution very much over a presenter, since a presenter should provide a new view on the data which is not possible with the traditional restriction modes.

**Comment by luisa-beerboom** [comment]
> What this presenter should return is basically the relation `committee/receive_forwardings_from_committee_ids`. If we change the restriction mode of this relation, the client can simply access this relation instead of calling a presenter. Since the dropdown in the client is visible if the user has `motion.can_manage`, I would suggest to implement a new restriction mode `C` for committees which says: "The user must have the permission `motion.can_manage` in at least one meeting of the committee". I would favor this solution very much over a presenter, since a presenter should provide a new view on the data which is not possible with the traditional restriction modes.

I think it's a good idea, we just need to make sure that these committees don't show up in the clients committee list

**Comment by jsangmeister** [comment]
Ah, right, we'll have to change the committee's "can see" property then as well and the restriction mode of `committee/name`. I forgot that the relation itself does not suffice. Maybe a presenter is the better approach then after all.

**Comment by jsangmeister** [comment]
Discussed with @luisa-beerboom: We'll go with the new presenter. It should be named something like `get_forwarding_committees` and take a committee id as a payload and return a list of strings consisting of the names of all committees contained in the relation `committee/receive_forwardings_from_committee_ids` of the committee given in the payload.
