### ISSUE TITLE
Add feature „lock participants out of a meeting“

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-backend#2498]
See https://github.com/OpenSlides/OpenSlides/issues/6756#issuecomment-2159989520 for reference
**Wanted behaviour:**
- [x] If locked out the participant is still in the meeting
- [x] A participant with the permission of user.canManage can lock out users without user.canManage permission or cml or oml permissions.
 - [x] It should be possible to change is_locked_out and the group (with canManage rights) at the same time, as long as you try to activate a combination which is allowed 
- [x] What should happen you try to assign a group with canManage permission to a locked out participant?
     - [x] You are told that this is a locked out participant and you cannot give this participant canManage rights until you lift the lock out first 
     - [x] participant edit-dialog: you should be able to select any group but if you select a group with canManage rights and you try to save it an Error should be thrown: It should tell you that a locked out participant is not allowed to have user.canManage rights and you have to lift the lockout first

- [x] What should happen you try to lockout a participant with canManage permission?
     - [x] You are told that this is a participant with canManage rights and you cannot lock out such participants until they lose this right
- [x] Who can NOT be locked out: 
    - [x] You from yourself
    - [x] (Meeting-) Admins
    - [x] participant with user.canManage permission
    - [x] Superadmins
    - [x] Orgaadmins
    - [x] Accountadmins
    - [x] Committeeadmins (but only from their own committees)
- [x] Who can be locked out: 
    - [x] Every User in a meeting who does not  have the permission participant.canManage
    - [x] Committeeadmins (but only from meetings where they are not committeeadmins)

- [x] Imports: 
    - [x] If the import is faulty (you try to lock out <-> assign canManage rights) then the import should be stopped and every line which is faulty should have the error symbol

**Comment by luisa-beerboom** [comment]
During a discussion with @emanuelschuetze and @MSoeb it came up that lockout status for a meeting _should always be settable_, regardless of whether the meeting is archived or not.

**Comment by luisa-beerboom** [comment]
> * A participant with the permission of user.canManage can lock out users without user.canManage permission or cml or oml permissions.

@Elblinator @MSoeb @emanuelschuetze 
What about the user.can_update permission? It is usually used in the user.update to update meeting-internal fields. Should it really not be permitted with that permission?

**Comment by MSoeb** [comment]
How should we handle users with user.can_update permission:
- [ ] users with this permission can lock out other users from the meeting; except the ones which are listed above that should not be locked out.
- [ ] users with the user.can_update permission can not lock themselves out
- [ ] users with user.canManage permission CAN lock out users with user.can_update permission, because the update permission is not an admin level and therefor it should be possible to lock them out.

@luisa-beerboom If I have missed a point or a perspective, please let me know.

**Comment by luisa-beerboom** [comment]
>     * [ ]  users with user.canManage permission CAN lock out users with user.can_update permission, because the update permission is not an admin level and therefor it should be possible to lock them out.

So everyone with (explicit or implicit) user.can_manage rights should be able to lock out users with can_update, (Superadmin, Meetingadmin, Participant with a group that has user.can_manage), only users who have user.can_update alone should not be able to lock out other users with can_update permission, but can still set everyone else who doesn't have any of the two permissions?

I don't see what the use-case behind that is, can you tell me? Otherwise I'd say it seems rather convoluted and will only further complicate this already complicated implementation. I'd advocate for either allowing everyone with field-appropriate permissions to set the field when updating user.can_update people or forbidding it for everyone.

**Comment by Elblinator** [comment]
as far as I understood it it is wanted that users with user.canUpdate should be able to lock out other participants and can be locked out by other particiants.

my gut feeling it telling me that canUpdate peopple can lock out other canUpdate people (@MSoeb?)

**Comment by luisa-beerboom** [comment]
Todo:
Look at meeting_user-specific actions
