### ISSUE TITLE
Rename default branch from master to main

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#287]
See https://www.techrepublic.com/article/github-to-replace-master-with-main-starting-in-october-what-developers-need-to-know/.

It's about renaming the default main branch which is currently called master.

**Comment by jsangmeister** [comment]
Oh, I didn't know they were enforcing it, I thought it was just about new repos...

**Comment by normanjaeckel** [comment]
No, they do not enforce it as I understood but we should change nevertheless ...

**Comment by FinnStutzenstein** [comment]
>  but we should change nevertheless

Regarding the discussion (which comes to live from time to time): I understand the reason behind it (also only partially, since we as germans to not have the history of slavery, but image it is called "leader", ...). But we should not do it partially, but be consistent in the complete organisation (every repo...). Otherwise there will be much confusion and I do not know how many scripts will break in our deployment. Also I think that *now* is not the right point to do it.

**Comment by jsangmeister** [comment]
> they do not enforce it

Citation: "By the end of the year, all existing repositories will be migrated to the new naming convention."

Sounds like they will enforce it, so we'll have to do it anyway. @FinnStutzenstein when would be the right point to do it? :D We will always be working on something and scripts may always break, we will probably never find a right time. Maybe someone has more detailed information on if and when the forced change comes?

**Comment by normanjaeckel** [comment]
As I understood GitHub will provide a smart migration path by the end of the year. So we can change all our repos at this time.

**Comment by FinnStutzenstein** [comment]
Closing for now, If we do this, this should be a coordinated move.
