### ISSUE TITLE
Action Response

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#32]
At the moment our actions do not respond anything. But the spec expects some kind of response. So this has to be implemented.

**Comment by normanjaeckel** [comment]
@ThomasJunk This is also a small issue to get to know my first draft for actions service. It is not a must have but if you like you may have a look at this. Feel free.

**Comment by FinnStutzenstein** [comment]
THe most common response would be the empty one since the read-path of the data flow is going through the autoupdate service. There are some exceptions (I definitely missed some):
- When creating an object, the id is returned (so that the client can open the detail page)
- Import views have typically return values indicating which entries have been imported and which have errored.
- sending emails to users

**Comment by FinnStutzenstein** [comment]
Additionally, the interface must be improved: The response is not just a message, but can be arbitrary json (https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/interfaces/actions-service.txt)

**Comment by ThomasJunk** [comment]
This issue has #27 as a prerequisite.
So I am deferring this to the point when the discussion on #27 settled

**Comment by ThomasJunk** [comment]
Independently, I made a suggestion regarding the [interface description](https://github.com/OpenSlides/OpenSlides/pull/5343).

**Comment by jsangmeister** [comment]
I think this is obsolete now
