### ISSUE TITLE
Adjust Datastore interface (implement collection field locks with filter)

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#384]
Add warning in backend if collection field lock filter does not contain meeting_id, since this will be indexed.

_Originally posted by @jsangmeister in https://github.com/OpenSlides/openslides-datastore-service/issues/105#issuecomment-756020827_

**Comment by jsangmeister** [comment]
Concrete example:

We are creating a model `c/3` which has a field `parent_id` describing some kind of hierarchy and a field `number` which should always be max + 1 of all fields `c/number` that belong to the same parent. Suppose we already have `c/1` and `c/2` with the same parent (let's say `parent_id=1`) and `c/1/number=1`, `c/2/number=2`. We use the `max` function with the filter `parent_id=1` and get `2` as a result. We write into our `locked_fields`: `{"c/number": {"position": <pos>, "filter": {"field": "parent_id", "operator": "=", "value": 1}`.

Now some other action sets `c/2/parent_id=2` (so our result is no longer valid). But, since it falls out of the filter, the change is not detected while executing the write request of the first action and the write request succeeds, which means we have invalid data in our DB.

One workaround is to lock all collection fields which are used in the filter to the given position, but without using the filter there (e.g. in this example, add `"c/parent_id": <pos>` to the locked fields). This seems unreasonable since then we could just go ahead and lock `c/number` to the exact position, without a filter. I think this is a general issue of this concept, but maybe we can circumvent it with the right locking in the backend.

Do you have a solution @FinnStutzenstein ?

**Comment by FinnStutzenstein** [comment]
Do you remember when I proposed a datastore-read-duplica added to the datastore adapter and if we had done this, we cannot use min/max anymore?

I think the problem with min/max is that we are loosing information. The way it would work is doing a filter and calculating min/max in the datastore adapter. This way, you get information about the actual models looked at during this calculation. You can now lock all these models.

I think this is the right way because the datastore proved information about models that must be locked, so the result stays valid.

> One workaround is to lock all collection fields

This is what all sorting actions should do. A sorting action (like the second one since it modified the tree structure) should lock in this example `c/parent_id` and `c/number` with the filter `meeting_id=xx`. One could argue, that the first action of creating a model is also a sort action, or a creation and sorting, so it should lock in the same way. I would agree, but since this is not performant, we should use the proposal above.

**Comment by FinnStutzenstein** [comment]
Maybe min/max should only be used, if the result is irrelevant for locking.

In you example: 2 is invalid, since it is not the maximum anymore (1 would be). But you want it to be `max+1`, so a real higher value than all other concurring models. This is still true! So, if there are no other restrictions (e.g. it must be **exactly** `max+1`, ad not `>=`), you can still use the result. Other cases:
- If you add a model to the parent node, the filter would catch it since the parent id-filter includes the new child
- If you change the number of `c/1` or `c/2`, this is also caught by the filter.

So if your code only needs to have the number bigger than every other number of the children of the same parent, it is fine (If I did not oversaw other cases). This includes, that it also can be bigger or smaller than other numbers of other parts of the tree.

**Comment by jsangmeister** [comment]
Ok, so min/max will NOT support locking.

**Comment by jsangmeister** [comment]
We have the same problem for `exists` and `count`, right? So these 4 function will all not support locking (which basically means they can no longer be used...)

**Comment by jsangmeister** [comment]
Or rather: They don't support locking via filters.

**Comment by FinnStutzenstein** [comment]
I'm unsure what the status in the backend is (especially with the proposal in #518 ). A solution would be (as stated above) that everything that aggregates on a filter (`min`, `max`, `count`, `exists`) must be done in the backend. For min/max you have to just query the one field and the id. For exists/count you just need the id- > you know which models were found by the filter and you can lock them directly.

Alternative (new proposal): The DS can include a list of ids matched by the filter in the response. This would also deny the usage of aggregating queries in postgresql, but it is the same as always using `filter` from outside.

**Comment by jsangmeister** [comment]
Rather than changing the datastore again, I would prefer the first approach. This was also my first idea. A shame that we needlessly implemented 4 methods in the datastore then...

**Comment by FinnStutzenstein** [comment]
> A shame that we needlessly implemented 4 methods in the datastore then...

Someone who does not need locking can still use them. But yeah, they are rather small. The filter part has taken the most effort if I remember correctly.
