### ISSUE TITLE
Enable sending values for user template fields

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#422]
After #421 is merged the user create and update actions have to be extended again to take values for the new template fields comment, number, structure_level, about_me and vote_weight. See the $-fields in models.yml.

**Comment by normanjaeckel** [comment]
This affects common users and tmp users (but they in another way because there is only one meeting, maybe some values have to be saved in default_* field) and also the update_self action.

**Comment by FinnStutzenstein** [comment]
I think this is the same task as for vote weight and group ids already. We should use the solution from group ids and vote weight for these fields, too, to keep consistent.

**Comment by jsangmeister** [comment]
Yes. My suggestion, based on the current implementations:
```
{
  x_$_y: {
    1: [1, 2],
    2: [1, 2]
    3: [],
    4: None
  }
}
```
as a payload sent by the client, with the current model looking like this:
```
{
  x_$_y: ["2", "3", "4", "5"],
  x_$2_y: [3, 4],
  x_$3_y: [1],
  x_$4_y: [1],
  x_$5_y: [1, 2],
}
```
would result in the following update event sent to the datastore:
```
{
  x_$_y: ["1", "2", "3", "5"],
  x_$1_y: [1, 2],
  x_$2_y: [1, 2],
  x_$3_y: [],
  x_$4_y: None,  // field is deleted
}
```
Some remarks:
1. Replacements that are given will completely overwrite any existing value (see `x_$2_y`)
2. Replacements that are not given at all will be left the way they were (see `x_$5_y` which is not present in the update to the datastore)

Collorary from (1) and (2): Not all replacements have to be given, but those that are given must be complete, meaning contain the whoe new value.

3. `[]` and `None` is a difference. I would suggest to not change this since we also have structured fields which are not lists and we'd have to differentiate between them then.

Remarks? Improvements?

**Comment by FinnStutzenstein** [comment]
Approved by @GabrielInTheWorld  and me, so it is ok for the client. As Gabriel stated: `simple but powerful`. I can only agree ;)
