### ISSUE TITLE
Add get_deleted_models flag for aggregate functions

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#447]
After requesting `motion_submitters.delete` with payload `{ id: 16 }` (`user_id: 3`) and readding the same user with the following payload:
```
{ 
action: "motion_submitter.create"
data: [{ motion_id: 12, user_id: 3 }]
}
```

throws the following error:
```
Fehler: (user_id, motion_id) must be unique
```

Is there anything wrong with the payloads? Do you need more information?

**Comment by jsangmeister** [comment]
This is a bug in the backend. It is similar to https://github.com/OpenSlides/openslides-backend/issues/207, which was fixed with https://github.com/OpenSlides/openslides-backend/pull/233: The `exists` method returns results of all models, even the deleted ones. Analogous to https://github.com/OpenSlides/openslides-backend/pull/233, we should implemented a flag which adds the filter for `meta_deleted` to the given filter if needed. The same needs to be done for `count`, `min`, `max`, before we run into the same problem again ;)
