### ISSUE TITLE
Need a way to test actions with anonymous user

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-backend#476]
We need a way to test the actions with request.user is an anonymous user.

**Comment by jsangmeister** [comment]
This should be fairly easy to implement: We need a second test client where no one is logged in (see https://github.com/OpenSlides/openslides-backend/blob/fdce3d0d2a46ee5b4ca50fb70b84badae6fefe42/tests/util.py#L23, the constructor takes `username`/`password` arguments; client is created [here](https://github.com/OpenSlides/openslides-backend/blob/fdce3d0d2a46ee5b4ca50fb70b84badae6fefe42/tests/system/base.py#L56)). The tests will of course only work for meetings where the anonymous is enabled, so maybe we should write a helper method that creates such a meeting (we wanted to have more helper methods for the tests anyway). The same schema can be followed to create a client with e.g. a normal user logged in instead of an admin.

The other possibility would be to login/logout the user on one client manually, but I favor the first approach.
