### ISSUE TITLE
Remove docker-compose files

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#59]
I think this repo does not need docker compose setup.

If you want to run the service manually you can use the Makefile with a nice docker command. If you want to use it with other services you should use a docker compose file in the main repository.

(In difference to e. g. datastore which requires third party services like postgresql to work.)

**Comment by FinnStutzenstein** [comment]
This service should provide system tests, meaning the service(s) running without any mocking, ...
You need a way to test the communication with external services. To automatically test this, a docker compose setup is a great way to spin all needed services up. There are other ways to manage this, but this way might be the convinent one. Please try to write the first system test, so you see, what you need to do it.

**Comment by FinnStutzenstein** [comment]
For development, the Dockerfile-dev should be enough, since the main development in the complete integration setup is done in the main repo. You may just make sure, that things like tests, `flake8`, ... are runnable in the dev container with `docker exec -ti openslides-backend flake8` (The syntax might be a bit different).

Please have the global make target `run-tests` im mind, that should do all sorts of tests, including style checking.

**Comment by normanjaeckel** [comment]
Ok, I remove docker compose for production but leve a stub for development / testing.
