### ISSUE TITLE
Refine base_permission_test

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#609]
The `base_permission_test` method is not sufficient enough to test the required permission.

It should set up a scenario of a user assigned to the meeting having all permissions except the one required.

What should be tested? E.g. `motion_block.create` needs `motion.can_manage`. Maybe there is a mistake and someone wrote `motion.can_see`. This should be noticed.

**Comment by FinnStutzenstein** [comment]
discussed: not needed

**Comment by jsangmeister** [comment]
I think I missunderstood this during our discussion. I agree with @FinnStutzenstein and @r-peschke that the base permission test should test more than that the user doesn't belong to the meeting - this test is redundant since it yields the same result for all actions. A more specific test, like suggested above, would be better.

**Comment by jsangmeister** [comment]
Maybe even multiple tests which are automatically executed, analogous to the existing permission tests in `test_permissions.py`
