### ISSUE TITLE
User restructure: Delete temporary actions

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#679]

**Comment by jsangmeister** [comment]
While updating the models, I had to delete them all because some needed fields were deleted. However, neither did I check exhaustively whether some mixins etc. can also be deleted nor did I check if some code may be recycled for the new permission checks. Someone should Ctrl+F through the whole repo for all instances of the deleted fields (e.g. `guest_ids`, `member_ids`, etc.) and delete all remaining instances as soon as the models update is finished.

**Comment by reiterl** [comment]
Checked: `member_ids, manager_ids, guest_ids, guest_meeting_ids, temporary_user_ids, marked`.
Found one surplus guest_meeting_ids, and one guest_ids in one comment.
