### ISSUE TITLE
Check if implementation is SOLID (enough)

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#7]
@tsiegleauq or @FinnStutzenstein May some of you check the current master concerning SOLID principles? I tried to follow a clean path from outside (``core.py``) to inside (``models``) without circular imports and thelike. (@tsiegleauq: This version differs from the version you reviewed last week esp. concerning used interfaces and exceptions.)

Have a look at ``.travis.yml`` to see, how to run the tests. Testing with Docker is still missing.

Also almost all adapters (to database, event store and permission service) are missing. Only the authentication adapter is ready.

If you are pleased, I can start implementing some more actions (and then try to use abstract action stuff). Implementing the adapters requires that we have correct interfaces to all other services.

Thanks a lot.

**Comment by tsiegleauq** [comment]
What I noticed:

It could make sense to have the [Application class](https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/core.py#L47) in it's own file, since it's fairly big.

In the topic create action:

It seems that some function will be used a lot and share essentially the very same logic.
Especially [check_permission_on_entry](https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/actions/topic/actions.py#L21) and [validate](https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/actions/topic/actions.py#L25)

There might be ways to archive more and write less code, i.e polymorphic or using decorators.

Furthermore: accessing string-fields ('topic.can_manage') is a kind of hard wiring. 

Everything else looks good so far

**Comment by normanjaeckel** [comment]
Ok, I will try the following:

* No hardwiring of permission strings. I will add some kind of map for it.
* Application class: Maybe I split up core.py into core/__init__.py, core/application.py and so on.
* The logic in topic create is more difficult. In the first step I will try to implement some more actions and then try to get some abstraction so that we have more generic code then,

**Comment by FinnStutzenstein** [comment]
### General

This review is a bit longer, but I tried to look at every part of the code so
far. The main structure looks ok, although there is still quite a mixture of
higher and lower policies. Some remarks may be a personal-style-thing, but
especially when it comes to dependency injection, please revisit the dependency
inversion principle. In this early phase we can reach such a decoupling, that
later on it will still be easily possible to separate this code, put parts in
libraries or add new services without any effort. I didn't noted the principles in the text,
but every proposed changed is based one at lest one of them.

### Main architectural view:
- The folder-structure needs to make space for other services: Permission,
  Restriction, Presenters
- These main components should be complete separated, e.g. subfolders and own
  packages (absolute imports)
- Cross-service imports should only be interface definitions (protocols)
- Services may share adapters/models/accessor-functions

The structure needs just a little modification:
```
backend/actions/ <-All action related stuff, especilly the registrar and disptcher
    /permissions
    /restriction
    /presenters
    /models
    /adapters (the "view-folder", see below)
    /shared (not general)
    /http (Werkzeug and other tools)
```

Each service (actions, presenter, permission, restriction) should have one
interface definition and one main service class implementing the interface. I
would suggest to call it as the name of the service. `actions/actions.py` with
the implementation, `actions/actions_interface.py` the interface (used as a
synonym for protocol, as it is a more general concept). In the `__init__.py`
import only the interface. So cross-service usage is limited to the interface
definition.

All code in the `core.py` is http-specific and should be moved into a http
folder. There should also be a base-view, and a view-registator (a decorator
analog to the actions), so when adding a new view, no code must be changed in
the http folder.

in the `openslides_backend` should only be a `main.py` (or `wsgi.py`), that
bootstraps the application. In this case it creates the wsgi-handler and maybe do
some dependency injection (see later).

There might multiple init.py's: In one case, there should be http-communication.
The "`http-main.py`" (or `wsgi.py`) creates the wsgi application and loads http
adapters for all services.
In another case the "`grpc-main.py`" also creates the wsgi application for
request handling, but loads grpc-adapters for all needed services. The main is
"the ultimate detail" and orchestrates the assembly of the application.

Please separate services and views more clearely: For example in the
`action_view.py`: The dispatch-part belongs to the service (interface:
`execute_action(name, data, user_id)`, which should be in the main
Action-service implementation in the action-folder. Error-handling with
status-codes and general format checking (is the Request valid) belongs to the
view. Also the authentication belongs to the view (and not dispatching) because
authentication is protocol-specific. It might differ, when using another
protocol than http.

The goal is, that services can use each other: The Action-Service needs to call
the permission service. The action-service only knows the interface. The
concrete implementation is provided by the main (via dependency-injection). It
may be an HttpAdapter or GrpcAdapter, but the action-service does not know about
this. In our case, it isn't an adapter, but the actual
permission-service-object. The permission-service-object is obtained via a
factory, provided by main. So if we want, we can split the permission service
easly into an own program by just moving the folder out of this structure and
create a SomeProtocolAdapter in this repo. There are no changes at all other
services in this repo, but only in the main, which provides the adapter (and
the interface definition might be duplicated). The goal in short is to kep the
services seperated from eachother and the technologies used.

### Actions

As stated above, the dispatcher should be a part of the action-module. Please do
not split the action class from the schema. They belong together in one file.
Also: Please create a file per action (not a catch-all `actions.py`) containing
the action class *and* the schema. Separate actions, not the implementation into
validation and execution.

Use some form of dependency-injection for the adapters. There is a package
available to do this. But a dependency injection is no to a little work in
python. The action-view currently mixes action-related logic with http
implementation (see above).

The action-view injects the permission- and database-adapter into the action.
This kind of DI is fine, but think about actions, that will need additional
services. Mediafile-actions wight need access to the mediafile-service to store
the action file. You may add the mediafile-service to the actions base class, but
than you have to adjust every action, even if only a bunch of them actually
needs the mediafile-service. So you need a better way for this dependency
injection. Maybe the actions should specify what they need and the concrete
implementations are provided via the DI (which in fact is setup by main).

### Inter-service-communication via DI

An additional point to the modularity goal from above: There will be two ways of
using a service (I'll take the permission service as an example): First, a
foreign service can query permissions via http/grpc. The action-service need to
query permissions. In the first case, there is an view/grpc-stub, called by the
http/grpc-stack, which uses the permission service.  In the second case, the
"internal" action-service (or any other) use the permission service directly.
This creates a common interface for both users. This is the interface I talked
about above. Because there might be multiple users, it must include all features
of the service, so do not move features to either an view/grpc-stub or other
"internal" services.

The dependency injection is important for the "internal
inter-service-communication" (permission-service <-> restriction-service <->
action-service <-> ...) and used to give a service access to another one.

### Adapterprotocols

These protocols must be defined in the action service. Currently there are
imports from the adapter package in the actions. This means, the actions know,
that there are adapters. This relationship has to be inverted. So you can just
move the protocols into the action part and let the adapters import the protocols
from the action service.

### Tests

For the current state of the code there are some tests missing. The ActionView
class, `register_action` and `perform` of the `Action` class are not tested. I do
see many integration tests that tests multiple classes at once (e.g. the
WSGITester tests `core.py`, `wsgi.py` and all views) but there are missing unit
tests. The TopicCreateAction is a good example, because it has both kinds of
tests. In the integration tests, `@patch` is often used; a proper DI would help
here.

**Comment by normanjaeckel** [comment]
Thank you very much.

I you like we can have a phone call tomorrow? Friday is my free-of-law-hacking day.

Some of your points I tried to solve by moving code all around. See https://github.com/OpenSlides/openslides-backend/pull/11.

Most interesting question for me is how to solve the dependency injection quest (or curse). Then we also should discuss whether all sub services of the OpenSlides Backend Service should run as WSGI applications. I thought the action service is something separate - an WSGI application that runs e. g. with gunicorn in its own container.

**Comment by normanjaeckel** [comment]
The current implementation provides the possibility to run the Docker container with one of the four subservices aka components. This is controlled by an environment variable. Three of them run a Gunicorn master process. One (I call it Addendum at the moment) is a single process (not written yet). During development one can start all four components with one command.

**Comment by normanjaeckel** [comment]
The structure should be clear now. Of course we may refactor this or that after some time ...
