### ISSUE TITLE
Duplicate/Clone or export meeting

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-backend#811]
To enable template meetings, we need the possibility to (either) duplicate (or clone) a meeting or to export an existing (OS4) meeting as JSON (or similar).

open questions for that:
- how to handle users (which might already exist in the organization)

**Comment by jsangmeister** [comment]
If you are cloning a meeting, you could use a similar logic to `meeting.import` except that you don't replace user ids. This would solve the user problem and should be reasonable to implement since the rest of the logic can be reused from the import action.

For the export side, the user problem would be harder to solve.

**Comment by FinnStutzenstein** [comment]
I agree: Exporting should be a simple task by just dumping all necessary things. It can be already imported, but the users are duplicated. So another (internal!) action `meeting.import_in_same_organization` is needed, that behaves equally as `meeting.import`, but just handles the users differently. Then a `meeting.clone` can be created which just executes `export` and `meeting.import_in_same_organization` subsequentially.

**Comment by reiterl** [comment]
Questions to the export:

- Have all parts of a meeting (like motion, poll, groups,...)  a meeting_id? So that I can filter for a collection with meeting_id?
- Where do I get the fields from? For the filter I need a list of fields as far as I know. The model.py?
- How to handle the special cases (orga, orga_tags, committee, user)? Especially the users need some filtering, or?

**Comment by FinnStutzenstein** [comment]
> Have all parts of a meeting (like motion, poll, groups,...) a meeting_id?

I think so, but check it in the models.yml

> Where do I get the fields from? For the filter I need a list of fields as far as I know. The model.py?

yes

> How to handle the special cases (orga, orga_tags, committee, user)?

Not exported. References to them must be cleared (e.g. `meeting/committee_id`, `meeting/organization_tag_ids`, ...)

> Especially the users need some filtering, or?

You need two modes:

1. **internal export**: Do not include users. This mode is used for internally cloning, so an import will directly follow. The import also need these two modes. Currently only the second one is implemented. The importer in this mode needs to skip everything user-related.[1]
2. **external export**: Include users. There must be everything stripped, that does not belong to the exported meeting.

[1] One thing came in my mind: The template fields with meeting ids as replacements needs to be duplicated from the old to the new meeting id.

> Are the export and the special import actions internal?

IDK how you will structure this, but maybe yes. We can decide it when you gave a first implementation I guess.

> Should the special import action use datavalidation? If both parts are internal, this is perhaps not needed.

Should not be needed, but would be good. Better to raise errors instead of importing invalid data.

**Comment by FinnStutzenstein** [comment]
@jsangmeister We have to thought about `motion/all_origin_ids` and `motion/all_derived_motion_ids` since they are relations that go outside of the meeting.

**Comment by jsangmeister** [comment]
> @jsangmeister We have to thought about `motion/all_origin_ids` and `motion/all_derived_motion_ids` since they are relations that go outside of the meeting.

Depends on the actual use case of the duplication, I would say. Maybe we should wait what @emanuelschuetze has to say here

**Comment by FinnStutzenstein** [comment]
Yes, I mean there are some options, but leaving it empty and e.g. `origin_id` set is inconsistent. What to do should be decided by @emanuelschuetze, right.

**Comment by GabrielInTheWorld** [comment]
> Update the action [meeting.clone](https://github.com/OpenSlides/OpenSlides/wiki/meeting.clone) in the wiki as necessary.

@reiterl and @jsangmeister What is the status here?

**Comment by tsiegleauq** [comment]
Exporting was more like 4.1, cloning should work
