### ISSUE TITLE
Add new presenter to get git commit IDs of all services

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#830]
Please add a new presenter that provides a list of all services together with all current commit IDs of this services. Therefor every service must provide its commit ID (e. g. inside the health answer). Host and ports of the services can be found in the env variables (see docker-compose.yml, e. g. https://github.com/OpenSlides/openslides-manage-service/blob/main/pkg/manage/docker-compose.yml.tpl and https://github.com/OpenSlides/openslides-manage-service/blob/main/pkg/manage/default_services.env).

Proposal: First add the presenter and provide the data only for the backend. Second: Client devs implement the view. Third: Open issues in all missing services to implement missing health data.

**Comment by jsangmeister** [comment]
Can you elaborate why we need this? As a versioning system or does it have a current use case besides that?

Also, it seems kinda hacky to archieve this. Since the git folder is not mounted inside the docker container and also git is not installed there (and I would vote against changing that), we probably would have to automatically (via GH actions?) copy the commit id to some local file which can then be read by the service. Or do you have an alternative in mind?

**Comment by normanjaeckel** [comment]
I am not sure how to solve this best. @emanuelschuetze wants to see in client during production the commit IDs or some version numbers of all (or at least the most important) services.

**Comment by tsiegleauq** [comment]
There might be a simpler idea for the time being, i.e injecting the commit hash of the main OS repo as a text to the client during docker build.

**Comment by jsangmeister** [comment]
Don't think we need this anymore atm.
