### ISSUE TITLE
Committee.update: manager_ids 

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#865]
Add manager_ids to the payload of committee.update.
The content of this field is a list of user_ids. Each user included get's the committee__management_level CAN_MANAGE or, if missing, will be removed as manager from the committee of the payload.

**Comment by reiterl** [comment]
We need to compare the managers in the db and the manager_ids. I don't see an easy way to get the manager from the db, because the manager is a permission in the user model in a templatefield. The only way I see to get them, is checking all user_ids if the user has the can_manage permission and collect them. Should I try this way?

**Comment by r-peschke** [comment]
> We need to compare the managers in the db and the manager_ids. I don't see an easy way to get the manager from the db, because the manager is a permission in the user model in a templatefield. The only way I see to get them, is checking all user_ids if the user has the can_manage permission and collect them. Should I try this way?

Try it this way:
    ```
   result = self.datastore.filter(
            Collection("user"),
            FilterOperator("committee_$1_management_level", "!=", None),   oo even better ("committee_$1_management_level", "=", "can_manage")
            ["id", "committee_$1_management_level"],
        )
```
This way you get all user's in this committe with manage-rights

**Comment by jsangmeister** [comment]
Should the removed managers remain part of the committee?
