### ISSUE TITLE
user.set_present_by_number

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#916]
Implement the new action `user.set_present_by_number`.
See [user.set_present_by_number](https://github.com/OpenSlides/OpenSlides/wiki/user.set_present_by_number) for further details.

**Comment by jsangmeister** [comment]
Since the action toggles the presence status instead of setting it, I think a name like `user.toggle_presence_by_number` would be more suitable.

Furthermore, this is inconsistent with the logic for `user.set_present` since there we explicitely give the new value. Is there a reason that we toggle the status instead here?

**Comment by GabrielInTheWorld** [comment]
> Since the action toggles the presence status instead of setting it, I think a name like `user.toggle_presence_by_number` would be more suitable.
> 

Okay for me.

> Furthermore, this is inconsistent with the logic for `user.set_present` since there we explicitely give the new value. Is there a reason that we toggle the status instead here?

This is the "as it is"-state in OS3. There, the present status of a user will be toggled by using this action.
